ItemNames_35 = {
    ["263371"] = {en = "Ensemble: Galactic Gladiator's Warrior Armor", zh = "套装：星河角斗士的战士护甲"},
    ["263372"] = {en = "Arsenal: Galactic Gladiator's Weapons", zh = "军械：星河角斗士的武器"},
    ["263373"] = {en = "You Can't Believe It's Not Void", zh = "你无法相信这不是虚空"},
    ["263374"] = {en = "Archivist's Epaulets", zh = "档案员的肩饰"},
    ["263375"] = {en = "Cultist's Shoulderpads", zh = "密教徒肩垫"},
    ["263376"] = {en = "Flaresong's Shoulderguards", zh = "炙歌护肩"},
    ["263377"] = {en = "Xal-a-Pal", zh = "萨拉宝贝"},
    ["263378"] = {en = "Dawnheart Pauldrons", zh = "拂晓之心肩铠"},
    ["263379"] = {en = "Personal Advertising Platform", zh = "个人宣传平台"},
    ["263380"] = {en = "Recruitment Pamphlets", zh = "征募宣传册"},
    ["263381"] = {en = "Xal'atath Wall Scrolls", zh = "萨拉塔斯壁挂卷轴"},
    ["263382"] = {en = "Twilight Material", zh = "暮光军备"},
    ["263383"] = {en = "Corked Bottle of Liquid Mystery", zh = "塞住的神秘液体瓶"},
    ["263384"] = {en = "Ensemble: Elite Galactic Gladiator's Death Knight Armor", zh = "套装：精锐星河角斗士的死亡骑士护甲"},
    ["263385"] = {en = "Ensemble: Elite Galactic Gladiator's Demon Hunter Armor", zh = "套装：精锐星河角斗士的恶魔猎手护甲"},
    ["263386"] = {en = "Ensemble: Elite Galactic Gladiator's Druid Armor", zh = "套装：精锐星河角斗士的德鲁伊护甲"},
    ["263387"] = {en = "Ensemble: Elite Galactic Gladiator's Evoker Armor", zh = "套装：精锐星河角斗士的唤魔师护甲"},
    ["263388"] = {en = "Ensemble: Elite Galactic Gladiator's Hunter Armor", zh = "套装：精锐星河角斗士的猎人护甲"},
    ["263389"] = {en = "Ensemble: Elite Galactic Gladiator's Mage Armor", zh = "套装：精锐星河角斗士的法师护甲"},
    ["263390"] = {en = "Ensemble: Elite Galactic Gladiator's Monk Armor", zh = "套装：精锐星河角斗士的武僧护甲"},
    ["263391"] = {en = "Ensemble: Elite Galactic Gladiator's Paladin Armor", zh = "套装：精锐星河角斗士的圣骑士护甲"},
    ["263392"] = {en = "Ensemble: Elite Galactic Gladiator's Priest Armor", zh = "套装：精锐星河角斗士的牧师护甲"},
    ["263393"] = {en = "Ensemble: Elite Galactic Gladiator's Rogue Armor", zh = "套装：精锐星河角斗士的潜行者护甲"},
    ["263394"] = {en = "Ensemble: Elite Galactic Gladiator's Shaman Armor", zh = "套装：精锐星河角斗士的萨满祭司护甲"},
    ["263395"] = {en = "Ensemble: Elite Galactic Gladiator's Warlock Armor", zh = "套装：精锐星河角斗士的术士护甲"},
    ["263396"] = {en = "Ensemble: Elite Galactic Gladiator's Warrior Armor", zh = "套装：精锐星河角斗士的战士护甲"},
    ["263397"] = {en = "Arsenal: Elite Galactic Gladiator's Weapons", zh = "军械：精锐星河角斗士的武器"},
    ["263400"] = {en = "Cache of Delver's Spoils", zh = "一箱地下堡行者的宝藏"},
    ["263413"] = {en = "Nullaeus Domaneye", zh = "努雷乌斯的统御之眼"},
    ["263416"] = {en = "Librarian's Woven Shoes", zh = "图书馆员的织履"},
    ["263419"] = {en = "Farstrider Recruit's Footwear", zh = "远行者新兵的便鞋"},
    ["263427"] = {en = "Eversong Naturalist's Boots", zh = "永歌博物学家的靴子"},
    ["263429"] = {en = "Eversong Hoofcovers", zh = "永歌蹄垫"},
    ["263433"] = {en = "Overflowing Silvermoon Trove", zh = "满溢的银月城宝箱"},
    ["263437"] = {en = "Gidwin's Tarnished Ring", zh = "吉德文的褪色戒指"},
    ["263438"] = {en = "Tarenar's Dusty Loop", zh = "塔伦纳的蒙尘圆戒"},
    ["263442"] = {en = "Voidridden Domaneye", zh = "充盈虚空的统御之眼"},
    ["263443"] = {en = "Technique: Contract: The Hara'ti", zh = "工艺图：合约：哈籁提"},
    ["263444"] = {en = "Technique: Contract: The Silvermoon Court", zh = "工艺图：合约：银月宫廷"},
    ["263445"] = {en = "Technique: Contract: The Singularity", zh = "工艺图：合约：奇点特勤"},
    ["263446"] = {en = "Spare Murloc Suit", zh = "备用鱼人服"},
    ["263447"] = {en = "Eversong Chopper", zh = "永歌切斧"},
    ["263449"] = {en = "Fluffy Comfy Flying Quilt", zh = "毛茸茸的舒适飞毯"},
    ["263450"] = {en = "Gruffy Comfy Flying Quilt", zh = "粗犷的舒适飞毯"},
    ["263451"] = {en = "Comfy Bel'ameth Flying Quilt", zh = "舒适的贝拉梅斯飞毯"},
    ["263452"] = {en = "Comfy Silvermoon Flying Quilt", zh = "舒适的银月城飞毯"},
    ["263454"] = {en = "Thalassian Alchemist's Notebook", zh = "萨拉斯炼金师的笔记本"},
    ["263455"] = {en = "Thalassian Blacksmith's Journal", zh = "萨拉斯铁匠日志"},
    ["263456"] = {en = "Thalassian Engineer's Notepad", zh = "萨拉斯工程师的记事本"},
    ["263457"] = {en = "Thalassian Scribe's Journal", zh = "萨拉斯铭文师日志"},
    ["263458"] = {en = "Thalassian Jewelcrafter's Notebook", zh = "萨拉斯珠宝匠的笔记本"},
    ["263459"] = {en = "Thalassian Leatherworker's Journal", zh = "萨拉斯制皮匠日志"},
    ["263460"] = {en = "Thalassian Tailor's Notebook", zh = "萨拉斯裁缝的笔记本"},
    ["263461"] = {en = "Thalassian Skinner's Notes", zh = "萨拉斯剥皮师笔记"},
    ["263462"] = {en = "Thalassian Herbalist's Notes", zh = "萨拉斯草药师笔记"},
    ["263463"] = {en = "Thalassian Miner's Notes", zh = "萨拉斯语矿工笔记"},
    ["263464"] = {en = "Thalassian Enchanter's Folio", zh = "萨拉斯附魔师对开纸"},
    ["263465"] = {en = "Surplus Bag of Party Favors", zh = "盈余的派对礼品袋"},
    ["263466"] = {en = "Overflowing Abundant Satchel", zh = "满溢的丰饶背包"},
    ["263467"] = {en = "Avid Learner's Supply Pack", zh = "好学者的补给包"},
    ["263471"] = {en = "Fire Thing", zh = "着火的东西"},
    ["263473"] = {en = "Recipe: Flora Frenzy", zh = "配方：植物狂宴"},
    ["263480"] = {en = "Eversong Rod", zh = "永歌魔棒"},
    ["263481"] = {en = "Eversong Protector", zh = "永歌保卫者"},
    ["263482"] = {en = "Eversong Stabber", zh = "永歌刺刃"},
    ["263484"] = {en = "Eversong Blade", zh = "永歌利刃"},
    ["263485"] = {en = "Eversong Battleaxe", zh = "永歌战斧"},
    ["263486"] = {en = "Eversong Hacker", zh = "永歌劈斧"},
    ["263487"] = {en = "Eversong Training Staff", zh = "永歌训练法杖"},
    ["263488"] = {en = "Companion Experience", zh = "伙伴经验值"},
    ["263489"] = {en = "Naaru's Enfold", zh = "纳鲁的拥怀"},
    ["263492"] = {en = "Blitzcreek", zh = "迅溪"},
    ["263499"] = {en = "Sturdy Void Elf Trunk", zh = "牢固的虚空精灵宝箱"},
    ["263500"] = {en = "Skymaster's Blood Mantle", zh = "飞行管理员的血红披肩"},
    ["263501"] = {en = "Skymaster's Blood Cloak", zh = "飞行管理员的血红披风"},
    ["263502"] = {en = "Skymaster's Blood Tabard", zh = "飞行管理员的血红战袍"},
    ["263503"] = {en = "Skymaster's Blood Circlet", zh = "飞行管理员的血红头环"},
    ["263504"] = {en = "Skymaster's Blood Pauldrons", zh = "飞行管理员的血红护肩"},
    ["263508"] = {en = "Human Brain", zh = "人类思考仪"},
    ["263510"] = {en = "Overflow Diverter", zh = "过载分流器"},
    ["263515"] = {en = "Broken Soulstealing Mirror", zh = "破碎的窃魂之镜"},
    ["263516"] = {en = "Cosmic Ritual Bowl", zh = "宇宙仪式之碗"},
    ["263517"] = {en = "Ancient Text", zh = "古代文献"},
    ["263518"] = {en = "Expensive-Looking Find", zh = "看起来很贵重的发现"},
    ["263519"] = {en = "Snake Oil", zh = "蛇油"},
    ["263520"] = {en = "Ensemble: Sprawling's Garb", zh = "套装：盘延罩衫"},
    ["263572"] = {en = "Tabard of the Gilded Collapsed Star", zh = "鎏金坍缩之星战袍"},
    ["263573"] = {en = "Pauldrons of the Gilded Collapsed Star", zh = "鎏金坍缩之星护肩"},
    ["263574"] = {en = "Ensemble: Osseoclad's Wear", zh = "套装：骨覆之装"},
    ["263575"] = {en = "Ensemble: Elder Moss Outfit", zh = "套装：长老的苔藓装束"},
    ["263576"] = {en = "Ensemble: Rampant Thorn Armor", zh = "套装：猖獗荆棘护甲"},
    ["263577"] = {en = "Arsenal: Rootlands Weaponry", zh = "军械：根野之地武器"},
    ["263579"] = {en = "Vivacious Chloroceros", zh = "活泼的叶绿犀龙"},
    ["263580"] = {en = "Vivid Chloroceros", zh = "鲜艳的叶绿犀龙"},
    ["263723"] = {en = "Shawl of the Gilded Collapsed Star", zh = "鎏金坍缩之星披巾"},
    ["263870"] = {en = "Rookery Cache Key", zh = "栖巢宝箱钥匙"},
    ["263871"] = {en = "Holy Pet Leash", zh = "神圣宠物绳"},
    ["263872"] = {en = "Lucifern", zh = "炼狱花"},
    ["263897"] = {en = "Radiant Jewelbinder", zh = "光耀珠宝镶嵌器"},
    ["263933"] = {en = "Preyseeker's Hearthstone", zh = "寻猎者的炉石"},
    ["263934"] = {en = "Chest of Gold", zh = "一箱黄金"},
    ["263938"] = {en = "Idol of Peril", zh = "危机神像"},
    ["263974"] = {en = "Relaxing Tisane", zh = "舒缓药茶"},
    ["263975"] = {en = "Feeling Fielder Mk. 7", zh = "氛围射放器Mk.7型"},
    ["263976"] = {en = "Bundle of Adventurer Dawncrests", zh = "装满冒险者曙光纹章的包裹"},
    ["263977"] = {en = "Venerable Satchel of Veteran Dawncrests", zh = "装满老兵曙光纹章的可敬背包"},
    ["263994"] = {en = "Fungal Chest", zh = "真菌之箱"},
    ["263995"] = {en = "Delver's Bountiful Coffer", zh = "地下堡行者的丰裕宝匣"},
    ["263996"] = {en = "Twilight Tabernacle", zh = "暮光圣体盒"},
    ["263997"] = {en = "Midnight Alchemist's Shop Sign", zh = "至暗之夜炼金师的店面标识"},
    ["263998"] = {en = "Midnight Blacksmith's Shop Sign", zh = "至暗之夜锻造师的店面标识"},
    ["263999"] = {en = "Midnight Cook's Shop Sign", zh = "至暗之夜厨师的店面标识"},
    ["264000"] = {en = "Midnight Enchanter's Shop Sign", zh = "至暗之夜附魔师的店面标识"},
    ["264001"] = {en = "Midnight Engineer's Shop Sign", zh = "至暗之夜工程师的店面标识"},
    ["264002"] = {en = "Midnight Fisher's Shop Sign", zh = "至暗之夜渔夫的店面标识"},
    ["264003"] = {en = "Midnight Herbalist's Shop Sign", zh = "至暗之夜草药师的店面标识"},
    ["264004"] = {en = "Midnight Scribe's Shop Sign", zh = "至暗之夜铭文师的店面标识"},
    ["264005"] = {en = "Midnight Jewelcrafter's Shop Sign", zh = "至暗之夜珠宝匠的店面标识"},
    ["264006"] = {en = "Midnight Leatherworker's Shop Sign", zh = "至暗之夜制皮师的店面标识"},
    ["264007"] = {en = "Corewarden's Spoils", zh = "核心守卫的战利品"},
    ["264008"] = {en = "Root-Wrapped Reliquary", zh = "根缚遗物匣"},
    ["264010"] = {en = "Galactic Gladiator's Prestigious Cloak", zh = "星河角斗士的尊崇斗篷"},
    ["264164"] = {en = "Galactic Gladiator's Tabard", zh = "星河角斗士的战袍"},
    ["264165"] = {en = "Tiff", zh = "蒂芙"},
    ["264166"] = {en = "Void Artifact Shard", zh = "虚空神器碎片"},
    ["264168"] = {en = "Cenarion Round Rug", zh = "塞纳里奥圆形毯子"},
    ["264169"] = {en = "Homestone Doormat", zh = "镇宅门毯"},
    ["264170"] = {en = "Ancient Kaldorei Coffer", zh = "上古卡多雷宝箱"},
    ["264172"] = {en = "Midnight Miner's Shop Sign", zh = "至暗之夜矿工的店面标识"},
    ["264173"] = {en = "Midnight Skinner's Shop Sign", zh = "至暗之夜剥皮师的店面标识"},
    ["264174"] = {en = "Midnight Tailor's Shop Sign", zh = "至暗之夜裁缝的店面标识"},
    ["264175"] = {en = "Amani Strongbox", zh = "阿曼尼保险箱"},
    ["264178"] = {en = "Harandar Charcuterie Board", zh = "哈籁恩达尔熟食板"},
    ["264182"] = {en = "Kelum'ko's Generous Aromatic Gift", zh = "格鲁姆科的慷慨“芬芳”赠礼"},
    ["264183"] = {en = "Kelum'ko's Generous Aromatic Gift", zh = "格鲁姆科的慷慨“芬芳”赠礼"},
    ["264184"] = {en = "Arsenal: Heirlooms of Atal'Aman", zh = "军械：阿塔阿曼传家宝"},
    ["264187"] = {en = "Blessed Phoenix Egg", zh = "受祝福的凤凰蛋"},
    ["264188"] = {en = "Golden Vidious Card", zh = "金色维迪奥斯卡牌"},
    ["264189"] = {en = "Golden Ziadan Card", zh = "金色兹尔丹卡牌"},
    ["264191"] = {en = "Ziadan's Stolen Battleplans", zh = "兹尔丹被盗的作战计划"},
    ["264192"] = {en = "Vidious' Stolen Battleplans", zh = "维迪奥斯被盗的作战计划"},
    ["264193"] = {en = "Amani Skyhunter's Sight", zh = "阿曼尼天空猎手的瞄具"},
    ["264194"] = {en = "Amani Flamebinder's Staff", zh = "阿曼尼缚焰者法杖"},
    ["264195"] = {en = "Amani Fangcaller's Spear", zh = "阿曼尼唤牙者之矛"},
    ["264196"] = {en = "Amani Warbringer's Edge", zh = "阿曼尼战争使者的利斧"},
    ["264197"] = {en = "Amani Spiritbark Ward", zh = "阿曼尼灵皮护盾"},
    ["264241"] = {en = "Crimson Bow Tie", zh = "赤红领结"},
    ["264242"] = {en = "Dreadscar Battle Planning Map", zh = "恐痕作战规划地图"},
    ["264243"] = {en = "Firm Haranir Pillow", zh = "结实的哈籁尼尔枕头"},
    ["264244"] = {en = "Plush Haranir Leather Pillow", zh = "毛绒哈籁尼尔皮革枕头"},
    ["264245"] = {en = "Warm Haranir Blanket", zh = "温暖的哈籁尼尔毯子"},
    ["264246"] = {en = "Eerie Iridescent Riftshroom", zh = "诡异的虹彩裂隙菇"},
    ["264248"] = {en = "Sin'dorei Storage Jar", zh = "辛多雷储物罐"},
    ["264249"] = {en = "Woodblock Stool", zh = "木块凳子"},
    ["264253"] = {en = "Galactic Void-Scarred Barricade", zh = "星河虚痕路障"},
    ["264254"] = {en = "Three-Tier Zul'Aman Shelf", zh = "三层祖阿曼架子"},
    ["264255"] = {en = "Amani Trophy Frame", zh = "阿曼尼战利品框"},
    ["264257"] = {en = "Zul'Aman Armament Rest", zh = "祖阿曼武器架"},
    ["264258"] = {en = "Blossoming Forge", zh = "盛放熔炉"},
    ["264259"] = {en = "On'ohia's Call", zh = "昂欧西雅的呼唤"},
    ["264262"] = {en = "Haranir Whistling Arrow", zh = "哈籁尼尔鸣镝"},
    ["264264"] = {en = "Gilded Vigil Post", zh = "鎏金警戒岗哨"},
    ["264265"] = {en = "Sanctified Flame Lantern", zh = "圣化烈焰灯笼"},
    ["264266"] = {en = "Lightbloom Moss Mound", zh = "光绽苔藓堆"},
    ["264267"] = {en = "Rutaani Birdfeeder", zh = "芦塔尼喂鸟器"},
    ["264268"] = {en = "Rutaani Birdbath", zh = "芦塔尼鸟浴盆"},
    ["264269"] = {en = "Rutaani Bird Perch", zh = "芦塔尼鸟栖木"},
    ["264273"] = {en = "Fel Spirehawk", zh = "邪能尖塔飞鹰"},
    ["264274"] = {en = "Fabled Adventurer's Cache", zh = "载誉冒险者的宝箱"},
    ["264278"] = {en = "Sturdy Portable Ice Chest", zh = "牢固的便携冰柜"},
    ["264279"] = {en = "Tall Corked Bottle of Liquid Mystery", zh = "高款塞住的神秘液体瓶"},
    ["264280"] = {en = "Short Corked Bottle of Liquid Mystery", zh = "矮款塞住的神秘液体瓶"},
    ["264281"] = {en = "Preserved Gift of Gilneas", zh = "吉尔尼斯的封存礼物"},
    ["264282"] = {en = "Bluebird's Golden Cage", zh = "蓝鸟的金丝笼"},
    ["264283"] = {en = "Backboard and Hoop Playset", zh = "篮板与篮筐玩具组"},
    ["264286"] = {en = "Voidbreaker's Choker", zh = "虚空粉碎者颈链"},
    ["264287"] = {en = "Voidbreaker's Circle", zh = "虚空粉碎者法戒"},
    ["264288"] = {en = "Voidbreaker's Ring", zh = "虚空粉碎者戒指"},
    ["264289"] = {en = "Wraps of Threadless Control", zh = "无序掌控裹手"},
    ["264290"] = {en = "Gloves of Threadless Control", zh = "无序掌控手套"},
    ["264291"] = {en = "Gauntlets of Threadless Control", zh = "无序掌控手甲"},
    ["264292"] = {en = "Grips of Threadless Control", zh = "无序掌控之握"},
    ["264293"] = {en = "Exile's Tattered Shawl", zh = "流亡者的破旧披肩"},
    ["264294"] = {en = "Nethersent Eredar's Cloak", zh = "虚空来客艾瑞达斗篷"},
    ["264295"] = {en = "Nightbreaker's Bands", zh = "碎夜束腕"},
    ["264296"] = {en = "Nightbreaker's Bracers", zh = "碎夜护腕"},
    ["264297"] = {en = "Nightbreaker's Cuffs", zh = "碎夜腕轮"},
    ["264298"] = {en = "Nightbreaker's Vambraces", zh = "碎夜护臂"},
    ["264299"] = {en = "Viral Coagulation Belt", zh = "疫病凝结腰带"},
    ["264300"] = {en = "Viral Coagulation Sash", zh = "疫病凝结饰带"},
    ["264301"] = {en = "Viral Coagulation Girdle", zh = "疫病凝结腰甲"},
    ["264302"] = {en = "Viral Coagulation Cinch", zh = "疫病凝结腰链"},
    ["264303"] = {en = "Willie", zh = "威列"},
    ["264304"] = {en = "Robes of Darkened Deceit", zh = "黑暗诡计长袍"},
    ["264305"] = {en = "Vest of Darkened Deceit", zh = "黑暗诡计外衣"},
    ["264306"] = {en = "Mail of Darkened Deceit", zh = "黑暗诡计锁甲"},
    ["264307"] = {en = "Breastplate of Darkened Deceit", zh = "黑暗诡计胸甲"},
    ["264308"] = {en = "Mask of Awakened Shadows", zh = "觉醒暗影面罩"},
    ["264309"] = {en = "Helmet of Awakened Shadows", zh = "觉醒暗影头盔"},
    ["264310"] = {en = "Cowl of Awakened Shadows", zh = "觉醒暗影兜帽"},
    ["264311"] = {en = "Warhelm of Awakened Shadows", zh = "觉醒暗影战盔"},
    ["264325"] = {en = "Mantle of the Stormarion Defender", zh = "斯托玛兰防御者衬肩"},
    ["264326"] = {en = "Pauldrons of the Stormarion Defender", zh = "斯托玛兰防御者护肩"},
    ["264327"] = {en = "Spaulders of the Stormarion Defender", zh = "斯托玛兰防御者肩甲"},
    ["264328"] = {en = "Shoulderpads of the Stormarion Defender", zh = "斯托玛兰防御者肩铠"},
    ["264329"] = {en = "Amani Dining Table", zh = "阿曼尼餐桌"},
    ["264330"] = {en = "Amani Hanging Brazier", zh = "阿曼尼悬挂火盆"},
    ["264332"] = {en = "Amani Ritual Altar", zh = "阿曼尼仪式祭坛"},
    ["264333"] = {en = "Amani Incense Burner", zh = "阿曼尼焚香炉"},
    ["264334"] = {en = "Amani War Drum", zh = "阿曼尼战鼓"},
    ["264335"] = {en = "Colossal Amani Stone Visage", zh = "巨型阿曼尼石像面具"},
    ["264336"] = {en = "Voidlight Brazier", zh = "虚光火盆"},
    ["264337"] = {en = "Cosmic Void Training Dummy", zh = "宇宙虚空训练假人"},
    ["264338"] = {en = "Domanaar Control Console", zh = "多曼纳尔控制台"},
    ["264339"] = {en = "Cosmic Void Summoning Crystal", zh = "宇宙虚空召唤水晶"},
    ["264340"] = {en = "Cosmic Barrel", zh = "宇宙之桶"},
    ["264341"] = {en = "Cosmic Void Crate", zh = "宇宙虚空箱子"},
    ["264342"] = {en = "Cosmic Void Cache", zh = "宇宙虚空宝箱"},
    ["264343"] = {en = "Cosmic Void Gravitational Orb", zh = "宇宙虚空引力宝珠"},
    ["264344"] = {en = "Cosmic Void Orb", zh = "宇宙虚空宝珠"},
    ["264345"] = {en = "Galactic Commander's Orb", zh = "星河指挥官的宝珠"},
    ["264349"] = {en = "Kun-Lai Lacquered Rickshaw", zh = "昆莱喷漆人力车"},
    ["264350"] = {en = "Carved Idol of Akil'zon, Loa of Victory", zh = "埃基尔松，凯旋之神雕像"},
    ["264351"] = {en = "Ornate Void Elf Banner", zh = "华丽虚空精灵旗帜"},
    ["264357"] = {en = "Void-Ridden Crab Meat", zh = "浸虚蟹肉"},
    ["264362"] = {en = "Golden Pandaren Privacy Screen", zh = "金色熊猫人私密屏风"},
    ["264363"] = {en = "Gar'chak Skullcleave's Head", zh = "加尔查克·裂颅的徽记"},
    ["264364"] = {en = "Hardin Steellock's Head", zh = "哈尔丁·钢锁的徽记"},
    ["264366"] = {en = "Razeshi C.", zh = "拉泽什·C"},
    ["264380"] = {en = "Contract of Service", zh = "效力契约"},
    ["264384"] = {en = "Zapmaster Viewer 3000", zh = "电击主宰观测器3000型"},
    ["264391"] = {en = "Sanctified Touch", zh = "圣化之触"},
    ["264396"] = {en = "Naturally Elegant Doormat", zh = "天然雅致门垫"},
    ["264397"] = {en = "Simply Adorned Vase and Flowers", zh = "朴素装饰的花瓶与花束"},
    ["264403"] = {en = "Repurposed Farstrider Slippers", zh = "翻新的远行者便鞋"},
    ["264404"] = {en = "Repurposed Farstrider Boots", zh = "翻新的远行者长靴"},
    ["264405"] = {en = "Repurposed Farstrider Treads", zh = "翻新的远行者踏靴"},
    ["264406"] = {en = "Repurposed Farstrider Stompers", zh = "翻新的远行者重靴"},
    ["264407"] = {en = "Void Resister's Pantaloons", zh = "抗虚者长裤"},
    ["264408"] = {en = "Void Resister's Leggings", zh = "抗虚者护腿"},
    ["264409"] = {en = "Void Resister's Greaves", zh = "抗虚者护胫"},
    ["264410"] = {en = "Void Resister's Legguards", zh = "抗虚者腿铠"},
    ["264411"] = {en = "Thief's Ring of Remembrance", zh = "窃贼的追忆之戒"},
    ["264412"] = {en = "Sin'dorei Magister's Keepsake", zh = "辛多雷魔导师的信物"},
    ["264413"] = {en = "Dominating Victory", zh = "统御凯旋"},
    ["264414"] = {en = "Midnight Delver's Flare Gun", zh = "至暗之夜地下堡行者的信号枪"},
    ["264415"] = {en = "Voidcaster's Bow", zh = "虚空法师之弓"},
    ["264417"] = {en = "Voidcaster's Greatsword", zh = "虚空法师巨剑"},
    ["264418"] = {en = "Voidcaster's Cleaver", zh = "虚空法师劈斧"},
    ["264419"] = {en = "Voidcaster's Scepter", zh = "虚空法师节杖"},
    ["264420"] = {en = "Voidcaster's Warglaive", zh = "虚空法师战刃"},
    ["264421"] = {en = "Voidcaster's Channeler", zh = "虚空法师引导法杖"},
    ["264422"] = {en = "Voidcaster's Dagger", zh = "虚空法师匕首"},
    ["264423"] = {en = "Voidcaster's Reaver", zh = "虚空法师掠夺斧"},
    ["264424"] = {en = "Voidcaster's Staff", zh = "虚空法师法杖"},
    ["264425"] = {en = "Voidformed Cleaver", zh = "虚化劈斧"},
    ["264426"] = {en = "Voidformed Smasher", zh = "虚化碎击锤"},
    ["264427"] = {en = "Voidformed Poker", zh = "虚化刺矛"},
    ["264428"] = {en = "Voidformed Shooter", zh = "虚化射手弓"},
    ["264429"] = {en = "Voidformed Slasher", zh = "虚化砍刀"},
    ["264430"] = {en = "Voidformed Stabber", zh = "虚化刺刀"},
    ["264431"] = {en = "Voidformed Caster", zh = "虚化施法器"},
    ["264432"] = {en = "Voidformed Protector", zh = "虚化护卫者"},
    ["264433"] = {en = "Voidformed Impaler", zh = "虚化穿刺者"},
    ["264434"] = {en = "Voldy", zh = "小虚"},
    ["264447"] = {en = "Ring of the Threshadon's Heart", zh = "蛇颈龙之心指环"},
    ["264448"] = {en = "Featherwoven Promise Band", zh = "羽织婚戒"},
    ["264449"] = {en = "Lightwood Logging Hatchet", zh = "光木伐木斧"},
    ["264450"] = {en = "Lightwood Carver's Knife", zh = "光木雕刻刀"},
    ["264451"] = {en = "Lightwood Spirit Cudgel", zh = "光木精魂棍"},
    ["264452"] = {en = "Lightwood Timber Maul", zh = "光木槌木锤"},
    ["264453"] = {en = "Lightwood Rune Blade", zh = "光木符文刃"},
    ["264454"] = {en = "Lightwood Forager's Saber", zh = "光木觅食者佩剑"},
    ["264455"] = {en = "Lightwood Crescent Blades", zh = "光木新月之刃"},
    ["264456"] = {en = "Lightwood Carved Longbow", zh = "光木雕花长弓"},
    ["264457"] = {en = "Lightwood Splitter Spear", zh = "光木劈裂长矛"},
    ["264458"] = {en = "Lightwood Channeling Staff", zh = "光木导能法杖"},
    ["264459"] = {en = "Lightwood Sunsword", zh = "光木阳炎之剑"},
    ["264460"] = {en = "Tuskcarver's Fang Knife", zh = "獠牙雕刻者的尖牙小刀"},
    ["264461"] = {en = "Tuskcarver's Ritual Maul", zh = "獠牙雕刻者的仪式大锤"},
    ["264462"] = {en = "Tuskcarver's Bone Hammer", zh = "獠牙雕刻者的白骨战锤"},
    ["264463"] = {en = "Tuskcarver's Hunt Blade", zh = "獠牙雕刻者的狩猎之刃"},
    ["264464"] = {en = "Tuskcarver's Sharpstaff", zh = "獠牙雕刻者的锐锋法杖"},
    ["264465"] = {en = "Tuskcarver's War Brand", zh = "獠牙雕刻者的战争烙印"},
    ["264466"] = {en = "Tuskcarver's Trophy", zh = "獠牙雕刻者的战利品"},
    ["264467"] = {en = "Tuskcarver's Shield", zh = "獠牙雕刻者之盾"},
    ["264468"] = {en = "Cloak of the Revantusk Rite", zh = "恶齿仪式披风"},
    ["264469"] = {en = "Ashbound Tribute Cloak", zh = "烬缚供奉斗篷"},
    ["264470"] = {en = "Ash-Tied Offering", zh = "灰缚贡品"},
    ["264471"] = {en = "Loa Impostor's Gloves", zh = "神灵伪装者手套"},
    ["264472"] = {en = "Loa Impostor's Clawguards", zh = "神灵伪装者爪卫护手"},
    ["264473"] = {en = "Loa Impostor's Tidegrips", zh = "洛阿伪装者潮握手甲"},
    ["264474"] = {en = "Loa Impostor's Brinefists", zh = "洛阿伪装者盐拳手铠"},
    ["264475"] = {en = "Umbral Tin Lockbox", zh = "幽影锡矿保险箱"},
    ["264477"] = {en = "Thunder Totem Mailbox", zh = "雷霆图腾邮箱"},
    ["264479"] = {en = "Skyweave Amani Tapestry", zh = "天织阿曼尼挂毯"},
    ["264480"] = {en = "Greenvine Amani Tapestry", zh = "绿藤阿曼尼挂毯"},
    ["264481"] = {en = "Earthhide Amani Tapestry", zh = "地皮阿曼尼挂毯"},
    ["264482"] = {en = "Void Elf Torch", zh = "虚空精灵火炬"},
    ["264483"] = {en = "Cosmic Void Campfire", zh = "宇宙虚空营火"},
    ["264491"] = {en = "Voidbound Holding Cell", zh = "虚缚牢笼"},
    ["264492"] = {en = "Chaotic Void Maw", zh = "混沌虚空渊门"},
    ["264493"] = {en = "Opened Domanaar Storage Crate", zh = "打开的多曼纳尔储物箱"},
    ["264494"] = {en = "Banded Domanaar Storage Crate", zh = "镶边多曼纳尔储物箱"},
    ["264497"] = {en = "Imperator's Torment Crystal", zh = "元首的折磨水晶"},
    ["264498"] = {en = "Voltaic Trigore Egg", zh = "流电三喉龙蛋"},
    ["264503"] = {en = "Cracked Core", zh = "碎裂的核心"},
    ["264506"] = {en = "Stormarion Fragment", zh = "斯托玛兰碎片"},
    ["264507"] = {en = "Crucible of Erratic Energies", zh = "异变能量坩埚"},
    ["264508"] = {en = "Sturdy Void Elf Barricade", zh = "牢固的虚空精灵路障"},
    ["264509"] = {en = "Void Elf Barrel", zh = "虚空精灵木桶"},
    ["264513"] = {en = "Crystalline Vessel", zh = "结晶容器"},
    ["264517"] = {en = "Galactic Flag of Victory", zh = "星河胜利旗帜"},
    ["264519"] = {en = "Repurposed Voidwalker's Chestplate", zh = "改装的虚空行者胸甲"},
    ["264520"] = {en = "Warden's Leycrook", zh = "守望者的魔网弯杖"},
    ["264521"] = {en = "Striderplume Focus", zh = "陆行鸟羽毛法器"},
    ["264522"] = {en = "Striderplume Armbands", zh = "陆行鸟羽毛臂环"},
    ["264523"] = {en = "Hydrafang Blade", zh = "多头蛇牙刃"},
    ["264524"] = {en = "Lightblighted Verdant Vest", zh = "光凋翠绿外套"},
    ["264525"] = {en = "Wrapped Antenna Cuffs", zh = "缠绕触角袖口"},
    ["264526"] = {en = "Supremely Slimy Sash", zh = "极度黏滑饰带"},
    ["264527"] = {en = "Vile Hexxer's Mantle", zh = "邪恶妖术师披肩"},
    ["264528"] = {en = "Goop-Coated Leggings", zh = "黏液涂层护腿"},
    ["264529"] = {en = "Cover of the Furbolg Elder", zh = "熊怪长者头罩"},
    ["264530"] = {en = "Grimfur Mittens", zh = "冷酷之毛手套"},
    ["264531"] = {en = "Shadowthread Slippers", zh = "暗影丝线便鞋"},
    ["264532"] = {en = "Robes of Flowing Truths", zh = "流动真理法袍"},
    ["264533"] = {en = "Queen's Tentacle Sash", zh = "女王的触手饰带"},
    ["264534"] = {en = "Bogvine Shoulderguards", zh = "沼泽藤蔓护肩"},
    ["264535"] = {en = "Leggings of the Cosmic Harrower", zh = "宇宙掠心者护腿"},
    ["264536"] = {en = "Zedling Summoning Collar", zh = "泽德的跟班召唤项圈"},
    ["264537"] = {en = "Winged Terror Gloves", zh = "有翼恐魔手套"},
    ["264538"] = {en = "Translucent Membrane Slippers", zh = "澄明薄膜便鞋"},
    ["264539"] = {en = "Robes of the Voidcaller", zh = "虚空召唤者法袍"},
    ["264540"] = {en = "Mirevine Wristguards", zh = "泥沼藤蔓护腕"},
    ["264541"] = {en = "Egg-Swaddling Sash", zh = "兽蛋襁褓饰带"},
    ["264542"] = {en = "Skullcrusher's Mantle", zh = "碎颅者披肩"},
    ["264543"] = {en = "Snapdragon Pantaloons", zh = "毒鳍龙长裤"},
    ["264544"] = {en = "Grounded Death Cap", zh = "触底的死亡面罩"},
    ["264545"] = {en = "Harrower-Claw Grips", zh = "掠心者锐爪护手"},
    ["264546"] = {en = "Bat Fur Boots", zh = "蝙蝠毛皮长靴"},
    ["264547"] = {en = "Worn Furbolg Bindings", zh = "破旧的熊怪裹腕"},
    ["264548"] = {en = "Sash of Cosmic Tranquility", zh = "寰宇宁静饰带"},
    ["264549"] = {en = "Ever-Devouring Shoulderguards", zh = "永恒吞噬护肩"},
    ["264550"] = {en = "Fungal Stalker's Stockings", zh = "真菌追猎者长袜"},
    ["264551"] = {en = "Nightbrood's Jaw", zh = "暮夜蜂之颚"},
    ["264552"] = {en = "Frogskin Grips", zh = "蛙皮之握"},
    ["264553"] = {en = "Deepspore Leather Galoshes", zh = "深孢皮革套鞋"},
    ["264554"] = {en = "Frilly Leather Vest", zh = "褶边皮甲"},
    ["264555"] = {en = "Splintered Hexwood Clasps", zh = "碎裂的妖木扣环"},
    ["264556"] = {en = "Voidforged Cinch", zh = "虚铸束带"},
    ["264557"] = {en = "Borerplate Pauldrons", zh = "钻孔板甲肩铠"},
    ["264558"] = {en = "Vileblood Resistant Sabatons", zh = "邪血抵抗战靴"},
    ["264559"] = {en = "Devourer's Visage", zh = "吞噬者面容"},
    ["264560"] = {en = "Sharpclaw Gauntlets", zh = "锐爪护手"},
    ["264561"] = {en = "Primal Bonestompers", zh = "原始碎骨战靴"},
    ["264562"] = {en = "Plated Grove Vest", zh = "板甲林地外套"},
    ["264563"] = {en = "Eruundi's Wristguards", zh = "厄卢恩蒂的护腕"},
    ["264564"] = {en = "Crab Wrangling Harness", zh = "驯蟹缰绳"},
    ["264565"] = {en = "Voidscale Shoulderpads", zh = "虚空鳞片肩垫"},
    ["264566"] = {en = "Lashtongue's Leaffroggers", zh = "鞭舌的踏叶便鞋"},
    ["264567"] = {en = "Rockscale Hood", zh = "石鳞兜帽"},
    ["264568"] = {en = "Serrated Scale Gauntlets", zh = "锯齿鳞片护手"},
    ["264569"] = {en = "Void-Gorged Kickers", zh = "噬虚踢靴"},
    ["264570"] = {en = "Reinforced Chainmrrl", zh = "强化的鱼人链甲"},
    ["264571"] = {en = "Ironleaf Wristguards", zh = "铁叶护腕"},
    ["264572"] = {en = "Netherplate Clasp", zh = "虚空板甲扣环"},
    ["264573"] = {en = "Taskmaster's Sadistic Shoulderguards", zh = "监工的施虐护肩"},
    ["264574"] = {en = "Netherterror's Legplates", zh = "虚空恐魔腿铠"},
    ["264575"] = {en = "Hexwood Helm", zh = "妖木头盔"},
    ["264576"] = {en = "Slatescale Grips", zh = "石板鳞片之握"},
    ["264577"] = {en = "Crystalforged Boots", zh = "晶铸长靴"},
    ["264578"] = {en = "Stumpy's Terrorplate", zh = "断株的恐魔板甲"},
    ["264579"] = {en = "Hungering Wristplates", zh = "饥渴腕铠"},
    ["264580"] = {en = "Mrrlokk's Mrgl Grrdle", zh = "莫尔洛克的咕噜束腰"},
    ["264581"] = {en = "Bloombark Spaulders", zh = "绽放树皮肩甲"},
    ["264582"] = {en = "Diamondback-Scale Legguards", zh = "菱纹背鳞护腿"},
    ["264583"] = {en = "Barbute of the Winged Hunter", zh = "翼猎者面甲"},
    ["264584"] = {en = "Stonecarved Smashers", zh = "石雕碎击拳套"},
    ["264585"] = {en = "Snapper Steppers", zh = "猛咬践踏者"},
    ["264586"] = {en = "Crustacean Carapace Chestguard", zh = "硬甲蟹壳胸甲"},
    ["264587"] = {en = "Ani's Trinket Bag", zh = "安妮的饰品袋"},
    ["264588"] = {en = "Shawl of Cosmic Whispers", zh = "寰宇低语披肩"},
    ["264589"] = {en = "Voidfused Wing Cloak", zh = "虚注飞翼披风"},
    ["264591"] = {en = "Radiant Petalwing's Feather", zh = "光耀瓣翼鸟的羽毛"},
    ["264592"] = {en = "Ha'kalawe's Flawless Wing", zh = "哈卡拉维的无瑕之翼"},
    ["264593"] = {en = "Warcloak of the Butcher", zh = "屠夫的战袍"},
    ["264594"] = {en = "Netherscale Cloak", zh = "虚鳞披风"},
    ["264595"] = {en = "Lynxhide Shawl", zh = "山猫皮披肩"},
    ["264596"] = {en = "Voidthread Veil", zh = "虚空织线面纱"},
    ["264597"] = {en = "Leechtooth Band", zh = "蛭牙指环"},
    ["264598"] = {en = "Eelectrum Signet", zh = "镍银印戒"},
    ["264599"] = {en = "Kul'Tiran Signet Ring", zh = "库尔提拉斯印戒"},
    ["264600"] = {en = "Ancient Argussian Band", zh = "远古阿古斯指环"},
    ["264601"] = {en = "Queen's Eye Band", zh = "女王之眼指环"},
    ["264602"] = {en = "Abyss Coral Band", zh = "深渊珊瑚指环"},
    ["264603"] = {en = "Guardian's Gemstone Loop", zh = "守护者的宝石圆戒"},
    ["264604"] = {en = "Sludgy Verdant Signet", zh = "污泥翠绿印戒"},
    ["264605"] = {en = "Choker of Unyielding Winds", zh = "不屈之风项圈"},
    ["264606"] = {en = "Netherlocus Amulet", zh = "虚空轨迹护符"},
    ["264607"] = {en = "Spore-Laden Choker", zh = "满孢项圈"},
    ["264608"] = {en = "String of Lovely Blossoms", zh = "可爱花串"},
    ["264609"] = {en = "Gar'chak's Mark of Honor", zh = "加尔查克的荣誉徽记"},
    ["264610"] = {en = "Escaped Specimen's ID Tag", zh = "逃逸的样本的身份标签"},
    ["264611"] = {en = "Pendant of Siphoned Vitality", zh = "虹吸活力吊坠"},
    ["264612"] = {en = "Tarnished Gold Locket", zh = "褪色的金挂坠盒"},
    ["264613"] = {en = "Steelbark Bulwark", zh = "钢皮壁垒"},
    ["264614"] = {en = "Fungal Cap Guard", zh = "菌盖卫士"},
    ["264615"] = {en = "Hardin's Backup Blade", zh = "哈尔丁的备用刀刃"},
    ["264616"] = {en = "Lightblighted Sapdrinker", zh = "光凋汲液者"},
    ["264617"] = {en = "Scourge's Spike", zh = "灾星尖刺"},
    ["264618"] = {en = "Strangely Eelastic Blade", zh = "奇异的鳗电之刃"},
    ["264619"] = {en = "Nethersteel Spellblade", zh = "虚空钢铸魔刃"},
    ["264620"] = {en = "Pufferspine Spellpierce", zh = "泡脊穿法者"},
    ["264621"] = {en = "Bad Zed's Worst Channeler", zh = "无恶不作的泽德的最差引导器"},
    ["264622"] = {en = "Grimfang Shank", zh = "冷酷之牙利刃"},
    ["264623"] = {en = "Shredding Fang", zh = "撕裂尖牙"},
    ["264624"] = {en = "Fang of the Dame", zh = "女爵利牙"},
    ["264625"] = {en = "Gale Force Focus", zh = "烈风法器"},
    ["264626"] = {en = "Scepter of Radiant Conversion", zh = "光辉转换节杖"},
    ["264627"] = {en = "Rav'ik's Spare Hunting Spear", zh = "拉维科的备用猎矛"},
    ["264628"] = {en = "Spear of Nothingness", zh = "虚无之矛"},
    ["264629"] = {en = "Coralfang's Hefty Fin", zh = "珊瑚之牙的厚重鳍刃"},
    ["264630"] = {en = "Colossal Voidsunderer", zh = "巨型虚空分裂者"},
    ["264631"] = {en = "Harak's Skullcutter", zh = "哈拉克的颅骨切割者"},
    ["264632"] = {en = "Darkblossom's Crook", zh = "暗绽的弯杖"},
    ["264633"] = {en = "Treetop Battlestave", zh = "树顶战杖"},
    ["264634"] = {en = "Spire of Flowing Void", zh = "流动虚空尖塔"},
    ["264635"] = {en = "Stumpy's Stump", zh = "断株的树桩"},
    ["264637"] = {en = "Cosmic Hunter's Glaive", zh = "寰宇猎手之刃"},
    ["264638"] = {en = "Fangs of the Invader", zh = "入侵者之牙"},
    ["264639"] = {en = "Razorfang Hacker", zh = "刃齿劈斧"},
    ["264640"] = {en = "Sharpened Borer Claw", zh = "锋利的钻取者之爪"},
    ["264641"] = {en = "Sharpened Skullcleaver", zh = "锋利的裂颅斧"},
    ["264642"] = {en = "Carving Voidscythe", zh = "虚镰蚀刻斧"},
    ["264643"] = {en = "Ash'an's Spare Cleaver", zh = "阿杉的备用劈斧"},
    ["264644"] = {en = "Crawler's Mindscythe", zh = "爬行者的魔镰"},
    ["264645"] = {en = "Aged Farstrider Bow", zh = "老旧的远行者之弓"},
    ["264646"] = {en = "Specimen Sinew Longbow", zh = "样本肌腱长弓"},
    ["264647"] = {en = "Cre'van's Punisher", zh = "科雷万惩罚者"},
    ["264648"] = {en = "Verminscale Gavel", zh = "害鼠鳞片木槌"},
    ["264649"] = {en = "Mindrot Claw-Hammer", zh = "溃心爪锤"},
    ["264650"] = {en = "Truthspreader's Truth Spreader", zh = "真理传播者的真理传播器"},
    ["264651"] = {en = "Resonating Traumatizer", zh = "共鸣创伤锤"},
    ["264652"] = {en = "Delver's Pouch of Voidlight Marl", zh = "地下堡行者的虚光灰岩袋子"},
    ["264654"] = {en = "Emberwing Hatchling", zh = "烬翼雏鸟"},
    ["264655"] = {en = "Amani Slate Bench", zh = "阿曼尼石板长椅"},
    ["264656"] = {en = "Void Elf Weapon Rack", zh = "虚空精灵武器架"},
    ["264657"] = {en = "Open Sturdy Void Elf Trunk", zh = "打开的牢固的虚空精灵宝箱"},
    ["264659"] = {en = "Cosmic Traveler's Satchel", zh = "宇宙旅行者背包"},
    ["264660"] = {en = "Ren'dorei Spired Tent", zh = "朗多雷尖顶帐篷"},
    ["264662"] = {en = "Robe of the Knife Priestess", zh = "尖刀女祭司长袍"},
    ["264663"] = {en = "Spiritdrain Vest of the Witherbark", zh = "枯木的吸魂外衣"},
    ["264664"] = {en = "Hexbreaker Chain Hauberk", zh = "破咒锁链胸甲"},
    ["264665"] = {en = "Defiant Loa Platebody", zh = "轻蔑神灵板甲"},
    ["264666"] = {en = "Rod of Exanguishation", zh = "放血之杖"},
    ["264668"] = {en = "Boon of Speed", zh = "速度恩典"},
    ["264669"] = {en = "Blessing of Potency", zh = "效能祝福"},
    ["264670"] = {en = "Blessing of Zeal", zh = "狂热祝福"},
    ["264672"] = {en = "Cosmic Ritual Stone", zh = "宇宙仪式之石"},
    ["264675"] = {en = "Cache from the Infinite's Armory", zh = "永恒军械库宝箱"},
    ["264676"] = {en = "Dalaran Sewer Gate", zh = "达拉然下水道大门"},
    ["264677"] = {en = "Rolled Scarab Rug", zh = "卷起来的甲虫之毯"},
    ["264678"] = {en = "Aspirant's Ringed Banner", zh = "候选者的环饰旗帜"},
    ["264679"] = {en = "Valdrakken Wall Shelf", zh = "瓦德拉肯壁挂架子"},
    ["264680"] = {en = "Cuddly Seagreen Grrgle", zh = "暖绒海绿色咕噜噜玩偶"},
    ["264681"] = {en = "Cuddly Brown Grrgle", zh = "暖绒棕色咕噜噜玩偶"},
    ["264682"] = {en = "Cuddly Flaxen Grrgle", zh = "暖绒亚麻色咕噜噜玩偶"},
    ["264683"] = {en = "Cuddly Sanguine Grrgle", zh = "暖绒血红色咕噜噜玩偶"},
    ["264684"] = {en = "Cuddly Gumball Grrgle", zh = "暖绒糖球色咕噜噜玩偶"},
    ["264685"] = {en = "Cuddly Violet Grrgle", zh = "暖绒紫罗兰色咕噜噜玩偶"},
    ["264686"] = {en = "Cuddly Olive Grrgle", zh = "暖绒橄榄绿色咕噜噜玩偶"},
    ["264687"] = {en = "Cuddly Plum Grrgle", zh = "暖绒李子色咕噜噜玩偶"},
    ["264688"] = {en = "Cuddly Tangerine Grrgle", zh = "暖绒橘红色咕噜噜玩偶"},
    ["264689"] = {en = "Cuddly Sapphire Grrgle", zh = "暖绒蓝宝石色咕噜噜玩偶"},
    ["264690"] = {en = "Cuddly Clover Grrgle", zh = "暖绒三叶草色咕噜噜玩偶"},
    ["264691"] = {en = "Cuddly Peach Grrgle", zh = "暖绒桃色咕噜噜玩偶"},
    ["264694"] = {en = "Ultradon Cuirass", zh = "巨凶龙胸甲"},
    ["264695"] = {en = "Interdimensional Parcel Signal", zh = "位面包裹信号器"},
    ["264701"] = {en = "Cosmic Bell", zh = "星界响铃"},
    ["264705"] = {en = "Glazed Sin'dorei Vial", zh = "上釉的辛多雷瓶子"},
    ["264706"] = {en = "Shadow Council Torch", zh = "暗影议会火把"},
    ["264707"] = {en = "Resizable All-Purpose Gear", zh = "可变尺寸的全能齿轮"},
    ["264708"] = {en = "Home Defense Gadget", zh = "家园防御装置"},
    ["264709"] = {en = "Stranglekelp Sack", zh = "荆棘藻包"},
    ["264710"] = {en = "Dalaran Sun Sconce", zh = "达拉然太阳灯台"},
    ["264711"] = {en = "Joybuzz's Joyful Wall of Trains", zh = "乔巴斯的欢乐火车墙"},
    ["264712"] = {en = "Gilnean Spare Saddle", zh = "吉尔尼斯闲置鞍座"},
    ["264713"] = {en = "Heart of the Forest Banner", zh = "森林之心旗帜"},
    ["264715"] = {en = "Zul'Aman Flame Cradle", zh = "祖阿曼火焰摇篮"},
    ["264717"] = {en = "Amani Warding Hex", zh = "阿曼尼防护妖术"},
    ["264805"] = {en = "Brann-O-Vision 3000", zh = "布莱恩视界3000型"},
    ["264847"] = {en = "Dozing Vinepouch", zh = "沉睡藤包"},
    ["264848"] = {en = "Sunlit Vinepouch", zh = "日晒藤包"},
    ["264849"] = {en = "Dewy Vinepouch", zh = "露湿藤包"},
    ["264851"] = {en = "Voidtouched Twilight Spaulder", zh = "虚触暮光肩甲"},
    ["264852"] = {en = "Bladed Twilight Spaulder", zh = "利刃暮光肩甲"},
    ["264853"] = {en = "Gilded Twilight Spaulder", zh = "鎏金暮光肩甲"},
    ["264854"] = {en = "Vilebranch Soulseer", zh = "邪枝灵魂先知"},
    ["264855"] = {en = "Vilebranch Deathseer", zh = "邪枝死亡先知"},
    ["264856"] = {en = "Vilebranch Lifeseer", zh = "邪枝生命先知"},
    ["264857"] = {en = "Twilight Fanatic's Cowl", zh = "暮光狂热者兜帽"},
    ["264859"] = {en = "Twilight Follower's Cowl", zh = "暮光追随者兜帽"},
    ["264860"] = {en = "Twilight Magus's Cowl", zh = "暮光大法师兜帽"},
    ["264878"] = {en = "Astalor's Anguish Agitator", zh = "阿斯塔洛的苦痛煽动者"},
    ["264882"] = {en = "Finery Funds", zh = "华服资金"},
    ["264883"] = {en = "Ensemble: Courtier's Crimson Vestments", zh = "套装：廷臣的赤红服饰"},
    ["264892"] = {en = "Nova", zh = "新星"},
    ["264895"] = {en = "Trials of the Florafaun Hunter", zh = "植生动物猎手的试炼"},
    ["264899"] = {en = "Arakkoan Alchemist's Concoction", zh = "鸦人炼金师的制剂"},
    ["264900"] = {en = "Arakkoan Alchemist's Bottle", zh = "鸦人炼金师的瓶子"},
    ["264907"] = {en = "Blood Knight Recruit's Shield", zh = "血骑士新兵盾牌"},
    ["264909"] = {en = "Flicker", zh = "烁烁"},
    ["264910"] = {en = "Shell-Cleaving Poleaxe", zh = "破甲长柄斧"},
    ["264911"] = {en = "Forest Hunter's Arc", zh = "森林猎手之弓"},
    ["264912"] = {en = "Void-Channeler's Spire", zh = "虚空引导者尖塔"},
    ["264913"] = {en = "Focused Netherslicer", zh = "凝神虚空之刃"},
    ["264915"] = {en = "Decorated Underground Table", zh = "精美的地下桌子"},
    ["264916"] = {en = "Loamm Bartering Stall", zh = "峈姆以物易物货摊"},
    ["264917"] = {en = "Ceramic Loamm Bowl", zh = "陶瓷峈姆碗"},
    ["264918"] = {en = "Zaralek Candles", zh = "查拉雷克蜡烛"},
    ["264919"] = {en = "Loamm Archway", zh = "峈姆拱门"},
    ["264920"] = {en = "Gooey Niffen Jar", zh = "黏糊糊的鼹鼠人罐子"},
    ["264921"] = {en = "Zaralek Snail Cart", zh = "查拉雷克蜗牛货车"},
    ["264922"] = {en = "Strong Sniffin' Incense", zh = "浓烈的嗅探熏香"},
    ["264923"] = {en = "Underdecorated Underground Table", zh = "简约的地下桌子"},
    ["264924"] = {en = "Loamm Wheelpot", zh = "峈姆转轮陶器"},
    ["264925"] = {en = "Kilnmaster's Bucket", zh = "掌窑者的水桶"},
    ["264968"] = {en = "Telluric Leyblossom", zh = "御土魔花"},
    ["264970"] = {en = "Oblivion's Edge", zh = "湮灭之锋"},
    ["264971"] = {en = "Annihilation Rod", zh = "歼灭之杖"},
    ["264972"] = {en = "Voidstorm Victuals", zh = "虚影风暴军粮"},
    ["264973"] = {en = "Goldenmist Gouda", zh = "金雾干酪"},
    ["264981"] = {en = "Goldengrove Juice", zh = "金色林地果汁"},
    ["264982"] = {en = "Wine Not", zh = "醉亦何妨"},
    ["264983"] = {en = "Sunwell Shot", zh = "太阳之井烈焰"},
    ["264984"] = {en = "Darkwell Draft", zh = "黑暗之井生啤"},
    ["264985"] = {en = "Dawnmosa", zh = "黎明含羞醉"},
    ["264987"] = {en = "Magister's Mead", zh = "魔导师蜂蜜酒"},
    ["264988"] = {en = "Endgame Essentials", zh = "终局必需品"},
    ["264989"] = {en = "Dragonhawk Flight", zh = "龙鹰特调"},
    ["264990"] = {en = "Fairbreeze Franciacorta", zh = "晴风法兰恰寇塔"},
    ["264991"] = {en = "Murder Roe", zh = "群鸦鱼子酱"},
    ["264992"] = {en = "Blood Knight Burger", zh = "血骑士汉堡"},
    ["264993"] = {en = "Delicate Dart Legs", zh = "精致镖蛙腿"},
    ["264994"] = {en = "Pickled Bloom Shoots", zh = "腌花芽"},
    ["264995"] = {en = "Goldenbough Preserves", zh = "金枝蜜饯"},
    ["264996"] = {en = "Gilded Sunlance", zh = "鎏金炎枪"},
    ["264997"] = {en = "Farstriders Quiver", zh = "远行者箭袋"},
    ["265014"] = {en = "Echo of Radiance", zh = "光辉回响"},
    ["265015"] = {en = "Echo of Radiance", zh = "光辉回响"},
    ["265016"] = {en = "Echo of Radiance", zh = "光辉回响"},
    ["265018"] = {en = "Ensemble: Courtier's Viridian Vestments", zh = "套装：廷臣的翠绿服饰"},
    ["265019"] = {en = "Ensemble: Courtier's Azure Vestments", zh = "套装：廷臣的碧蓝服饰"},
    ["265020"] = {en = "Ensemble: Courtier's Umbral Vestments", zh = "套装：廷臣的幽黑服饰"},
    ["265021"] = {en = "Ensemble: Courtier's Lucent Vestments", zh = "套装：廷臣的光白服饰"},
    ["265022"] = {en = "Ensemble: Augur's Crimson Garments", zh = "套装：占卜师的赤红衣着"},
    ["265023"] = {en = "Ensemble: Augur's Viridian Garments", zh = "套装：占卜师的翠绿衣着"},
    ["265024"] = {en = "Ensemble: Augur's Azure Garments", zh = "套装：占卜师的碧蓝衣着"},
    ["265025"] = {en = "Ensemble: Augur's Umbral Garments", zh = "套装：占卜师的幽黑衣着"},
    ["265026"] = {en = "Ensemble: Augur's Lucent Garments", zh = "套装：占卜师的光白衣着"},
    ["265027"] = {en = "Lucky Lynx Locket", zh = "幸运山猫挂坠盒"},
    ["265030"] = {en = "Kai", zh = "凯"},
    ["265032"] = {en = "Hearty Niffen Grub", zh = "丰盛的鼹鼠人餐食"},
    ["265035"] = {en = "Medusa", zh = "美杜莎"},
    ["265039"] = {en = "Silvermoon Splendor", zh = "银月城光辉"},
    ["265040"] = {en = "Fractured Void Focus", zh = "碎裂的虚空法器"},
    ["265041"] = {en = "Singed Ritual Parchment", zh = "烧焦的仪式羊皮纸"},
    ["265042"] = {en = "Tarnished Shadow Torque", zh = "晦暗的暗影颈环"},
    ["265043"] = {en = "Dented Voidblade Pommel", zh = "凹陷的虚空利刃柄头"},
    ["265044"] = {en = "Frayed Twilight Sash", zh = "磨损的暮光腰带"},
    ["265045"] = {en = "Sealed Blood Vial", zh = "封印血瓶"},
    ["265046"] = {en = "Warped Summoning Sigil", zh = "扭曲召唤符印"},
    ["265047"] = {en = "Cracked Soul Phylactery", zh = "破裂的灵魂护命匣"},
    ["265048"] = {en = "Scale Fragment", zh = "带鳞碎片"},
    ["265049"] = {en = "Drifting Conch Whistle", zh = "漂流海螺哨"},
    ["265050"] = {en = "Coral Shard", zh = "珊瑚碎片"},
    ["265051"] = {en = "Carved Root Totem", zh = "雕刻根须图腾"},
    ["265052"] = {en = "Crumbly Stone Shard", zh = "易碎的石块碎片"},
    ["265053"] = {en = "Gnarled Bark Shard", zh = "扭曲的树皮碎片"},
    ["265054"] = {en = "Cracked Tribal Mask", zh = "破裂的部落面具"},
    ["265055"] = {en = "Torn Dimensional Wrap", zh = "撕裂的维度裹布"},
    ["265056"] = {en = "Flickering Energy Coil", zh = "闪烁的能量线圈"},
    ["265057"] = {en = "Hollow Binding Strand", zh = "空心束缚丝线"},
    ["265058"] = {en = "Distorted Echo Fragment", zh = "扭曲的回响碎片"},
    ["265059"] = {en = "Collapsed Void Core", zh = "坍缩的虚空核心"},
    ["265061"] = {en = "Whispering Rift Residue", zh = "低语裂隙残渣"},
    ["265062"] = {en = "Nullflare Residue", zh = "虚空闪光残渣"},
    ["265071"] = {en = "Gleaming Sunmote", zh = "闪耀太阳微粒"},
    ["265072"] = {en = "Amani Fangstitch Quiver", zh = "阿曼尼尖牙缝合箭袋"},
    ["265096"] = {en = "Conjured Souffle", zh = "咒术舒芙蕾"},
    ["265097"] = {en = "Conjured Cinnamon Roll", zh = "魔法肉桂面包"},
    ["265098"] = {en = "Conjured Croissant", zh = "魔法羊角面包"},
    ["265099"] = {en = "Conjured Tea", zh = "咒术茶"},
    ["265100"] = {en = "Corewarden's Hearthstone", zh = "核心守卫的炉石"},
    ["265336"] = {en = "Faunatender's Trust", zh = "护林者的信赖"},
    ["265337"] = {en = "Aln'hara Sprigshot", zh = "艾林哈籁蔓枝弓"},
    ["265341"] = {en = "Thorncap", zh = "刺帽菇"},
    ["265361"] = {en = "Pollinic Incense", zh = "花粉熏香"},
    ["265362"] = {en = "Arsenal: Twilight Blade", zh = "军械：暮光之刃"},
    ["265363"] = {en = "Twilight Shadowguard's Hatchet", zh = "暮光影卫短柄斧"},
    ["265364"] = {en = "Twilight Infiltrator's Blade", zh = "暮光渗透者之刃"},
    ["265365"] = {en = "Twilight Duskwhisper Dagger", zh = "暮光黄昏低语者匕首"},
    ["265366"] = {en = "Twilight Executioner", zh = "暮光处刑者"},
    ["265367"] = {en = "Twilight Fang", zh = "暮光之牙"},
    ["265368"] = {en = "Twilight Destroyer", zh = "暮光毁灭者"},
    ["265387"] = {en = "Cuddly Tomato Grrgle", zh = "暖绒番茄色咕噜噜玩偶"},
    ["265388"] = {en = "Cuddly Lemon Grrgle", zh = "暖绒柠檬色咕噜噜玩偶"},
    ["265389"] = {en = "Cuddly Cotton Candy Grrgle", zh = "暖绒棉花糖色咕噜噜玩偶"},
    ["265390"] = {en = "Cuddly Mint Grrgle", zh = "暖绒薄荷色咕噜噜玩偶"},
    ["265391"] = {en = "Cuddly Magenta Grrgle", zh = "暖绒洋红色咕噜噜玩偶"},
    ["265392"] = {en = "Cuddly Sunset Grrgle", zh = "暖绒日落色咕噜噜玩偶"},
    ["265393"] = {en = "Cuddly Mauve Grrgle", zh = "暖绒淡紫色咕噜噜玩偶"},
    ["265394"] = {en = "Cuddly Pearl Grrgle", zh = "暖绒珍珠色咕噜噜玩偶"},
    ["265395"] = {en = "Cuddly Charcoal Grrgle", zh = "暖绒炭黑色咕噜噜玩偶"},
    ["265396"] = {en = "Cuddly Onyx Grrgle", zh = "暖绒玛瑙色咕噜噜玩偶"},
    ["265397"] = {en = "Cuddly Bright Grrgle", zh = "暖绒亮色咕噜噜玩偶"},
    ["265398"] = {en = "Cuddly Juniper Grrgle", zh = "暖绒杜松色咕噜噜玩偶"},
    ["265528"] = {en = "Plans: Gilded Silvermoon Anvil", zh = "图纸：鎏金银月城铁砧"},
    ["265530"] = {en = "Plans: Ornamental Silvermoon Hanger", zh = "图纸：纹饰银月城衣架"},
    ["265532"] = {en = "Plans: Gilded Silvermoon Hanger", zh = "图纸：鎏金银月城衣架"},
    ["265534"] = {en = "Plans: Ren'dorei Anvil", zh = "图纸：朗多雷铁砧"},
    ["265536"] = {en = "Plans: Masterwork Crafting Hammer", zh = "图纸：大师级锻造锤"},
    ["265541"] = {en = "Loammy Soil", zh = "峈姆的肥沃土壤"},
    ["265543"] = {en = "Tempered Amani Spearhead", zh = "淬火的阿曼尼矛头"},
    ["265544"] = {en = "Cuddly Basil Grrgle", zh = "暖绒罗勒色咕噜噜玩偶"},
    ["265545"] = {en = "Cuddly Void Grrgle", zh = "暖绒虚空色咕噜噜玩偶"},
    ["265546"] = {en = "Cuddly Fel Grrgle", zh = "暖绒邪能色咕噜噜玩偶"},
    ["265547"] = {en = "Cuddly Spectral Grrgle", zh = "暖绒幽灵色咕噜噜玩偶"},
    ["265548"] = {en = "Cuddly Emerald Grrgle", zh = "暖绒翡翠色咕噜噜玩偶"},
    ["265549"] = {en = "Cuddly Metallic Grrgle", zh = "暖绒金属色咕噜噜玩偶"},
    ["265550"] = {en = "Cuddly Verdant Grrgle", zh = "暖绒翠绿色咕噜噜玩偶"},
    ["265551"] = {en = "Cuddly Cobalt Grrgle", zh = "暖绒钴蓝色咕噜噜玩偶"},
    ["265552"] = {en = "Cuddly Teal Grrgle", zh = "暖绒青色咕噜噜玩偶"},
    ["265553"] = {en = "Cuddly Ochre Grrgle", zh = "暖绒赭石色咕噜噜玩偶"},
    ["265554"] = {en = "Reinforced Amani Haft", zh = "加固的阿曼尼矛柄"},
    ["265560"] = {en = "Toughened Amani Leather Wrap", zh = "坚韧的阿曼尼皮革裹带"},
    ["265562"] = {en = "Amani Warrior's Spear", zh = "阿曼尼战士长矛"},
    ["265601"] = {en = "Galactic Gladiator's Greataxe", zh = "星河角斗士的巨斧"},
    ["265609"] = {en = "Princess Bloodshed", zh = "沐血公主"},
    ["265611"] = {en = "Broken Picnic Basket", zh = "损坏的野餐篮"},
    ["265612"] = {en = "Galactic Gladiator's Dagger", zh = "星河角斗士的匕首"},
    ["265613"] = {en = "Galactic Gladiator's Warglaive", zh = "星河角斗士的战刃"},
    ["265614"] = {en = "Galactic Gladiator's Polearm", zh = "星河角斗士的长钺"},
    ["265615"] = {en = "Galactic Gladiator's Staff", zh = "星河角斗士的法杖"},
    ["265616"] = {en = "Galactic Gladiator's Bow", zh = "星河角斗士之弓"},
    ["265617"] = {en = "Galactic Gladiator's Scepter", zh = "星河角斗士的节杖"},
    ["265618"] = {en = "Galactic Gladiator's Tome", zh = "星河角斗士的魔典"},
    ["265619"] = {en = "Galactic Gladiator's Shield", zh = "星河角斗士的盾牌"},
    ["265621"] = {en = "Galactic Gladiator's Shattered Blade", zh = "星河角斗士的碎裂之刃"},
    ["265623"] = {en = "Galactic Gladiator's Slicer", zh = "星河角斗士的军刀"},
    ["265625"] = {en = "Galactic Gladiator's Blaster", zh = "星河角斗士的轰击炮"},
    ["265627"] = {en = "Galactic Gladiator's Greatsword", zh = "星河角斗士的巨剑"},
    ["265628"] = {en = "Galactic Gladiator's Morningstar", zh = "星河角斗士的晨星锤"},
    ["265629"] = {en = "Galactic Gladiator's Sword", zh = "星河角斗士之剑"},
    ["265630"] = {en = "Galactic Gladiator's Battlestaff", zh = "星河角斗士的战斗法杖"},
    ["265632"] = {en = "Galactic Gladiator's Hammer", zh = "星河角斗士的战锤"},
    ["265638"] = {en = "Galactic Gladiator's Greataxe", zh = "星河角斗士的巨斧"},
    ["265655"] = {en = "Ritual Components", zh = "仪式材料"},
    ["265656"] = {en = "Anu'shalla, Shadow's Guidance", zh = "阿努莎拉，暗影启迪"},
    ["265657"] = {en = "Fiber of Living Agony", zh = "活体苦痛纤维"},
    ["265658"] = {en = "Silvermoon Court Cloak", zh = "银月宫廷披风"},
    ["265659"] = {en = "Silvermoon Court Epaulets", zh = "银月宫廷肩饰"},
    ["265663"] = {en = "Silvermoon Court Tabard", zh = "银月宫廷战袍"},
    ["265664"] = {en = "Budding Light", zh = "初绽之光"},
    ["265665"] = {en = "Chanterelle Shandy", zh = "鸡油菌香蒂酒"},
    ["265666"] = {en = "World Root Beer", zh = "世界之根啤酒"},
    ["265667"] = {en = "Bright Claw", zh = "亮爪特饮"},
    ["265668"] = {en = "Har'kuai Mai Tai", zh = "哈库艾迈泰鸡尾"},
    ["265669"] = {en = "Fermented Rift Water", zh = "发酵裂隙之水"},
    ["265674"] = {en = "Tasty Meat", zh = "美味的肉"},
    ["265681"] = {en = "Preyseeker's Magister Effigy", zh = "寻猎者的魔导师雕像"},
    ["265682"] = {en = "Preyseeker's Tinker Effigy", zh = "寻猎者的工匠雕像"},
    ["265683"] = {en = "Preyseeker's Ethereal Effigy", zh = "寻猎者的虚灵雕像"},
    ["265684"] = {en = "Preyseeker's Breaker Effigy", zh = "寻猎者的击碎者雕像"},
    ["265685"] = {en = "Preyseeker's Amani Effigy", zh = "寻猎者的阿曼尼雕像"},
    ["265686"] = {en = "Preyseeker's Rutaani Effigy", zh = "寻猎者的芦塔尼雕像"},
    ["265687"] = {en = "Preyseeker's Vindicator Effigy", zh = "寻猎者的守备官雕像"},
    ["265688"] = {en = "Preyseeker's Consul Effigy", zh = "寻猎者的执政官雕像"},
    ["265689"] = {en = "Preyseeker's Executor Effigy", zh = "寻猎者的执行官雕像"},
    ["265690"] = {en = "Preyseeker's Knight-Errant Effigy", zh = "寻猎者的豪侠骑士雕像"},
    ["265691"] = {en = "Preyseeker's Wretched Effigy", zh = "寻猎者的迷失者雕像"},
    ["265692"] = {en = "Preyseeker's Thornspeaker Effigy", zh = "寻猎者的棘语者雕像"},
    ["265694"] = {en = "Preyseeker's Twilight Effigy", zh = "寻猎者的暮光雕像"},
    ["265695"] = {en = "Elementary Voidcore Shard", zh = "初级虚空核心碎片"},
    ["265696"] = {en = "Preyseeker's Magister Bust", zh = "寻猎者的魔导师半身像"},
    ["265697"] = {en = "Preyseeker's Tinker Bust", zh = "寻猎者的工匠半身像"},
    ["265698"] = {en = "Preyseeker's Ethereal Bust", zh = "寻猎者的虚灵半身像"},
    ["265699"] = {en = "Preyseeker's Breaker Bust", zh = "寻猎者的击碎者半身像"},
    ["265700"] = {en = "Preyseeker's Amani Bust", zh = "寻猎者的阿曼尼半身像"},
    ["265701"] = {en = "Preyseeker's Rutaani Bust", zh = "寻猎者的芦塔尼半身像"},
    ["265702"] = {en = "Preyseeker's Vindicator Bust", zh = "寻猎者的守备官半身像"},
    ["265703"] = {en = "Preyseeker's Consul Bust", zh = "寻猎者的执政官半身像"},
    ["265704"] = {en = "Preyseeker's Executor Bust", zh = "寻猎者的执行官半身像"},
    ["265705"] = {en = "Preyseeker's Knight-Errant Bust", zh = "寻猎者的豪侠骑士半身像"},
    ["265706"] = {en = "Preyseeker's Wretched Bust", zh = "寻猎者的迷失者半身像"},
    ["265707"] = {en = "Preyseeker's Thornspeaker Bust", zh = "寻猎者的棘语者半身像"},
    ["265708"] = {en = "Preyseeker's Twilight Bust", zh = "寻猎者的暮光半身像"},
    ["265714"] = {en = "Trovehunter's Bounty", zh = "珍宝猎手的奖赏"},
    ["265739"] = {en = "Amani Heartstring Pendant", zh = "阿曼尼心弦吊坠"},
    ["265740"] = {en = "Amani Totemstring", zh = "阿曼尼图腾索"},
    ["265746"] = {en = "Idol of Abundance", zh = "丰饶神像"},
    ["265767"] = {en = "Loaknit-Woven Catch Satchel", zh = "神愈织物捕获背包"},
    ["265768"] = {en = "Amazardhide Catch Case", zh = "甲脊蜥皮捕获包"},
    ["265769"] = {en = "Boarhide Catch Sack", zh = "野猪皮捕获袋"},
    ["265770"] = {en = "Triple-Thread Net", zh = "三股线网"},
    ["265771"] = {en = "Shallows Net", zh = "浅滩网"},
    ["265775"] = {en = "Amani Warrior Stave", zh = "阿曼尼战士法杖"},
    ["265778"] = {en = "Hollowcore Harpoon Turret", zh = "空核鱼叉炮台"},
    ["265779"] = {en = "Heavy Harpoon Cannon", zh = "重型鱼叉炮"},
    ["265781"] = {en = "Amani Spiritdancer's Boneweight", zh = "阿曼尼灵舞者骨坠"},
    ["265790"] = {en = "Cache of Dawncrests", zh = "曙光纹章宝箱"},
    ["265791"] = {en = "Haranir Canopy Bed", zh = "遮篷哈籁尼尔床"},
    ["265792"] = {en = "Fungarian Vine Fence", zh = "真菌人藤蔓围栏"},
    ["265794"] = {en = "Preyseeker's Plinth", zh = "寻猎者的基座"},
    ["265795"] = {en = "Preyseeker's Ornate Plinth", zh = "寻猎者的华丽基座"},
    ["265796"] = {en = "Preyseeker's Ren'dorei Effigy", zh = "寻猎者的朗多雷雕像"},
    ["265797"] = {en = "Preyseeker's Farstrider Effigy", zh = "寻猎者的远行者雕像"},
    ["265798"] = {en = "Preyseeker's Ren'dorei Bust", zh = "寻猎者的朗多雷半身像"},
    ["265799"] = {en = "Preyseeker's Farstrider Bust", zh = "寻猎者的远行者半身像"},
    ["265800"] = {en = "Earthy Garnish", zh = "大地风味饰菜"},
    ["265801"] = {en = "Savory Anomaly", zh = "咸香异物"},
    ["265802"] = {en = "Tome of Town Portal", zh = "城镇传送之书"},
    ["265803"] = {en = "Bazaar Bites", zh = "集市小吃"},
    ["265804"] = {en = "Sanctuary Chess Collection", zh = "庇护之地象棋收藏"},
    ["265814"] = {en = "Noble's Signet Ring", zh = "贵族印戒"},
    ["265816"] = {en = "Lost Quiver", zh = "遗失的箭袋"},
    ["265817"] = {en = "Forgotten Songwriter's Quill", zh = "被遗忘的作曲家羽毛笔"},
    ["265818"] = {en = "Ruia's Musings, Part 1", zh = "鲁伊亚沉思录，第一部分"},
    ["265819"] = {en = "Ruia's Musings, Part 2", zh = "鲁伊亚沉思录，第二部分"},
    ["265820"] = {en = "Ruia's Musings, Part 3", zh = "鲁伊亚沉思录，第三部分"},
    ["265822"] = {en = "Unstable Mechagon Re-Localizatron", zh = "不稳定的麦卡贡再定位器"},
    ["265824"] = {en = "The Rootwarden's Notes", zh = "护根者的笔记"},
    ["265828"] = {en = "Gilded Armillary Sphere", zh = "镀金浑天仪球体"},
    ["265832"] = {en = "Incomplete Booklet of Sonnets", zh = "未完成的十四行诗集"},
    ["265833"] = {en = "Page 1 of a Book of Sonnets", zh = "十四行诗集第一页"},
    ["265834"] = {en = "Page 2 of a Book of Sonnets", zh = "十四行诗集第二页"},
    ["265835"] = {en = "Page 3 of a Book of Sonnets", zh = "十四行诗集第三页"},
    ["265922"] = {en = "Pet Training Manual: Fetch", zh = "宠物训练手册：拾回"},
    ["265923"] = {en = "Pet Training Manual: Play Dead", zh = "宠物训练手册：装死"},
    ["265943"] = {en = "Firm Haranir Pillow", zh = "结实的哈籁尼尔枕头"},
    ["265945"] = {en = "Warm Haranir Blanket", zh = "温暖的哈籁尼尔毯子"},
    ["265946"] = {en = "Haranir Reclined Bed", zh = "哈籁尼尔斜靠床"},
    ["265949"] = {en = "March on Quel'Danas Vanquisher's Aureate Trophy", zh = "进军奎尔丹纳斯征服者的耀金战利品"},
    ["265950"] = {en = "Dreamrift Vanquisher's Aureate Trophy", zh = "梦境裂隙征服者的耀金战利品"},
    ["265951"] = {en = "Voidspire Vanquisher's Aureate Trophy", zh = "虚影尖塔征服者的耀金战利品"},
    ["265995"] = {en = "Quel'Thalas Adventurer's Cache", zh = "奎尔萨拉斯冒险家的宝箱"},
    ["265997"] = {en = "Blood Knight Champion's Tabard", zh = "血骑士勇士战袍"},
    ["266002"] = {en = "Broken Trap Mechanism", zh = "损坏的陷阱装置"},
    ["266075"] = {en = "Harpoon of Extirpation", zh = "灭绝鱼叉"},
    ["266076"] = {en = "Nether Siphoner", zh = "虚空虹吸者"},
    ["266077"] = {en = "Basic Black Quiver", zh = "基础黑色箭袋"},
    ["266078"] = {en = "Basic Blue Quiver", zh = "基础蓝色箭袋"},
    ["266079"] = {en = "Basic Bronze Quiver", zh = "基础青铜箭袋"},
    ["266080"] = {en = "Sentinel's Night Quiver", zh = "哨兵的夜色箭袋"},
    ["266081"] = {en = "Basic Dark Blue Quiver", zh = "基础深蓝箭袋"},
    ["266082"] = {en = "Basic Dark Red Quiver", zh = "基础暗红箭袋"},
    ["266083"] = {en = "Basic Frost Quiver", zh = "基础冰霜箭袋"},
    ["266084"] = {en = "Farstrider's Forest Quiver", zh = "远行者的森林箭袋"},
    ["266085"] = {en = "Basic Ice Quiver", zh = "基础冰晶箭袋"},
    ["266086"] = {en = "Basic Light Quiver", zh = "基础亮色箭袋"},
    ["266087"] = {en = "Basic Light Blue Quiver", zh = "基础浅蓝箭袋"},
    ["266088"] = {en = "Basic Light Brown Quiver", zh = "基础浅棕箭袋"},
    ["266089"] = {en = "Basic Pale Quiver", zh = "基础灰白箭袋"},
    ["266090"] = {en = "Basic Purple Quiver", zh = "基础紫色箭袋"},
    ["266091"] = {en = "Basic Rugged Quiver", zh = "基础坚固箭袋"},
    ["266092"] = {en = "Basic Sea Green Quiver", zh = "基础海绿箭袋"},
    ["266095"] = {en = "Obsidian Scale Treads", zh = "黑曜石鳞片战靴"},
    ["266096"] = {en = "Huntress' Moonglaive", zh = "女猎手的月刃"},
    ["266097"] = {en = "Huntress' Moonblade", zh = "女猎手的月刃剑"},
    ["266098"] = {en = "Faindel's Longbow", zh = "费恩德尔的长弓"},
    ["266099"] = {en = "Extinguished Exaliburn", zh = "熄灭的失约胜利之剑"},
    ["266100"] = {en = "Barbed Riftwalker Dirk", zh = "带刺的裂隙行者短剑"},
    ["266101"] = {en = "Unused Initiate's Bulwark", zh = "未使用的见习生壁垒"},
    ["266102"] = {en = "Ambiguous Rock", zh = "模棱两可的石头"},
    ["266120"] = {en = "Sisterhood's Crescent", zh = "姐妹会的新月刀"},
    ["266121"] = {en = "Sisterhood's Glaive", zh = "姐妹会的战刃"},
    ["266122"] = {en = "Archer's Night Sabre", zh = "射手的夜色军刀"},
    ["266123"] = {en = "Sisterhood's Moonlance", zh = "姐妹会的月之矛"},
    ["266124"] = {en = "Archer's Shadow Talon", zh = "射手的暗影利爪"},
    ["266125"] = {en = "Priestess' Starblade", zh = "女祭司的星刃"},
    ["266128"] = {en = "Aberration Part", zh = "畸变部件"},
    ["266160"] = {en = "Trapper's Green Slippers", zh = "捕兽者的绿色便鞋"},
    ["266183"] = {en = "Enigmatic Voidclarion", zh = "神秘的虚空号角"},
    ["266196"] = {en = "Ensemble: Preyseeker's Refined Armor", zh = "套装：寻猎者的精致护甲"},
    ["266197"] = {en = "Ensemble: Preyseeker's Sleek Armor", zh = "套装：寻猎者的光洁护甲"},
    ["266198"] = {en = "Ensemble: Preyseeker's Rugged Armor", zh = "套装：寻猎者的粗制护甲"},
    ["266199"] = {en = "Ensemble: Preyseeker's Polished Armor", zh = "套装：寻猎者的抛光护甲"},
    ["266207"] = {en = "Tarnished Dawnlit Spellbinder's Cloak", zh = "褪色的晨光缚法者披风"},
    ["266208"] = {en = "Tarnished Dawnlit Corsair's Shroud", zh = "褪色的晨光水手裹布"},
    ["266209"] = {en = "Tarnished Dawnlit Sentinel's Drape", zh = "褪色的晨光哨兵披巾"},
    ["266210"] = {en = "Tarnished Dawnlit Commander's Cape", zh = "褪色的晨光指挥官斗篷"},
    ["266213"] = {en = "Incense Materials", zh = "熏香材料"},
    ["266216"] = {en = "Threadbare Cloak", zh = "破旧的披风"},
    ["266221"] = {en = "Frayed Shroud", zh = "磨损的裹布"},
    ["266223"] = {en = "Stained Drape", zh = "脏污的披巾"},
    ["266224"] = {en = "Brittle Cape", zh = "易碎的斗篷"},
    ["266234"] = {en = "Saltfang Shoals Large Garden Cluster", zh = "咸牙浅滩大型花园簇"},
    ["266235"] = {en = "Razorwind Cactus Large Garden Cluster", zh = "烈风仙人掌大型花园簇"},
    ["266236"] = {en = "Razorwind Blooms Large Garden Cluster", zh = "烈风花卉大型花园簇"},
    ["266237"] = {en = "Runetotem's Bounty Large Garden Cluster", zh = "符文图腾的恩典大型花园簇"},
    ["266238"] = {en = "Cragthorn Highlands Large Garden Cluster", zh = "峭荆高地大型花园簇"},
    ["266239"] = {en = "Outer Banks Large Garden Cluster", zh = "外滩大型花园簇"},
    ["266240"] = {en = "Founder's Point Large Garden Cluster", zh = "创始者之角大型花园簇"},
    ["266241"] = {en = "Brumewood Hollow Large Garden Cluster", zh = "霾林谷大型花园簇"},
    ["266242"] = {en = "Gilded Oaks Large Garden Cluster", zh = "鎏金橡林大型花园簇"},
    ["266243"] = {en = "Stoneveil Ridge Large Garden Cluster", zh = "石帷山脊大型花园簇"},
    ["266244"] = {en = "Granite Cobblestone Path Corner", zh = "花岗岩卵石拐角"},
    ["266245"] = {en = "Granite Cobblestone Path Arc", zh = "花岗岩卵石路弧段"},
    ["266259"] = {en = "Altar of the Shul'ka", zh = "舒尔卡的祭坛"},
    ["266262"] = {en = "Dawnroot Haranir Channeler", zh = "Dawnroot Haranir Channeler"},
    ["266263"] = {en = "Wildgrove Haranir Longbow", zh = "荒林哈籁尼尔长弓"},
    ["266264"] = {en = "Sunpetal Haranir Spire", zh = "晨瓣哈籁尼尔塔杖"},
    ["266265"] = {en = "Windpetal Haranir Baton", zh = "风瓣哈籁尼尔指挥棒"},
    ["266266"] = {en = "Moonpetal Haranir Staff", zh = "月瓣哈籁尼尔法杖"},
    ["266267"] = {en = "Thornpierce Haranir Fang", zh = "荆刺哈籁尼尔之牙"},
    ["266269"] = {en = "Rootbound Haranir Aegis", zh = "根缚哈籁尼尔庇护盾"},
    ["266270"] = {en = "Witherbloom Haranir Staff", zh = "枯花哈籁尼尔法杖"},
    ["266271"] = {en = "Wildbloom Haranir Warblade", zh = "荒花哈籁尼尔战刃"},
    ["266314"] = {en = "Novice Combatant's Necklace", zh = "新手争斗者的项链"},
    ["266317"] = {en = "Novice Combatant's Ring", zh = "新手争斗者的指环"},
    ["266370"] = {en = "Dundun's Abundant Travel Method", zh = "钝顿的丰饶旅行方式"},
    ["266384"] = {en = "Sanctum Magister's Post", zh = "圣殿魔导师柱子"},
    ["266386"] = {en = "Sanctum Acolyte's Post", zh = "圣殿助祭柱子"},
    ["266387"] = {en = "Sanctum Magister's Pylon", zh = "圣殿魔导师晶塔"},
    ["266388"] = {en = "Sanctum Acolyte's Pylon", zh = "圣殿助祭晶塔"},
    ["266393"] = {en = "Farstrider's Gilded Bow", zh = "远行者鎏金长弓"},
    ["266396"] = {en = "Farstrider's Solemn Bow", zh = "远行者庄严长弓"},
    ["266429"] = {en = "Silvermoon Sunspire", zh = "银月城太阳之塔头冠"},
    ["266430"] = {en = "Silvermoon Sunguard", zh = "银月城日卫护面"},
    ["266431"] = {en = "Silvermoon Sunveil", zh = "银月城日纱兜帽"},
    ["266432"] = {en = "Silvermoon Suncrest", zh = "银月城日顶头盔"},
    ["266438"] = {en = "Idol of Pestilence", zh = "疫疾神像"},
    ["266440"] = {en = "Idol of Growth", zh = "生长神像"},
    ["266443"] = {en = "Granite Cobblestone Long Path", zh = "花岗岩卵石长路"},
    ["266444"] = {en = "Granite Cobblestone Path", zh = "花岗岩卵石路"},
    ["266885"] = {en = "March on Quel'Danas Vanquisher's Gleaming Trophy", zh = "进军奎尔丹纳斯征服者的闪耀战利品"},
    ["266886"] = {en = "Dreamrift Vanquisher's Gleaming Trophy", zh = "梦境裂隙征服者的闪耀战利品"},
    ["266887"] = {en = "Voidspire Vanquisher's Gleaming Trophy", zh = "虚影尖塔征服者的闪耀战利品"},
    ["266892"] = {en = "Neighborhood Campsites", zh = "社区营地"},
    ["266901"] = {en = "Depthdiver's Cloak", zh = "深潜者披风"},
    ["266902"] = {en = "Depthdiver's Tabard", zh = "深潜者战袍"},
    ["266903"] = {en = "Depthdiver's Shoulderpads", zh = "深潜者护肩"},
    ["266965"] = {en = "Tabard of Amani Abundance", zh = "阿曼尼丰饶战袍"},
    ["266966"] = {en = "Mantle of Amani Abundance", zh = "阿曼尼丰饶护肩"},
    ["266967"] = {en = "Shawl of Amani Abundance", zh = "阿曼尼丰饶披肩"},
    ["266968"] = {en = "Priestess' Starpoint", zh = "女祭司的星点匕首"},
    ["266969"] = {en = "Ensemble: Depthdiver Vestments", zh = "套装：深潜者服饰"},
    ["266970"] = {en = "Ensemble: Abundant Raiment", zh = "套装：丰饶衣着"},
    ["266979"] = {en = "Shawl of the Darkened Collapsed Star", zh = "黯淡坍缩之星披巾"},
    ["266980"] = {en = "Pauldrons of the Darkened Collapsed Star", zh = "黯淡坍缩之星护肩"},
    ["266981"] = {en = "Tabard of the Darkened Collapsed Star", zh = "黯淡坍缩之星战袍"},
    ["266982"] = {en = "Tabard of the Nebulous Collapsed Star", zh = "星云坍缩之星战袍"},
    ["266983"] = {en = "Pauldrons of the Nebulous Collapsed Star", zh = "星云坍缩之星护肩"},
    ["266984"] = {en = "Shawl of the Nebulous Collapsed Star", zh = "星云坍缩之星披巾"},
    ["266985"] = {en = "Hearty Silvermoon Parade", zh = "丰盛银月城浮华大餐"},
    ["266986"] = {en = "Hearty Quel'dorei Medley", zh = "丰盛奎尔多雷拼盘"},
    ["266996"] = {en = "Hearty Harandar Celebration", zh = "丰盛哈籁恩达尔庆典大餐"},
    ["267004"] = {en = "Twinblade of the Devourer", zh = "吞噬者双刃"},
    ["267005"] = {en = "Rakan's Totem", zh = "拉坎的图腾"},
    ["267007"] = {en = "Eye of Acherus", zh = "阿彻鲁斯之眼"},
    ["267008"] = {en = "Crucible Votive Rack", zh = "熔炉还愿物架"},
    ["267009"] = {en = "Amani Training Dummy", zh = "阿曼尼训练假人"},
    ["267012"] = {en = "Designs of the Grand Architect", zh = "建筑大师的设计图"},
    ["267040"] = {en = "Sea Caller", zh = "大海召唤者"},
    ["267052"] = {en = "Thalassian Alchemy Coveralls", zh = "萨拉斯炼金工装服"},
    ["267053"] = {en = "Pattern: Thalassian Alchemy Coveralls", zh = "图样：萨拉斯炼金工装服"},
    ["267054"] = {en = "Thalassian Chef's Chapeau", zh = "萨拉斯大厨烹饪帽"},
    ["267055"] = {en = "Pattern: Thalassian Chef's Chapeau", zh = "图样：萨拉斯大厨烹饪帽"},
    ["267056"] = {en = "Thalassian Enchanter's Bonnet", zh = "萨拉斯附魔师软帽"},
    ["267057"] = {en = "Pattern: Thalassian Enchanter's Bonnet", zh = "图样：萨拉斯附魔师软帽"},
    ["267060"] = {en = "Thalassian Herbalist's Cowl", zh = "萨拉斯草药师风帽"},
    ["267061"] = {en = "Pattern: Thalassian Herbalist's Cowl", zh = "图样：萨拉斯草药师风帽"},
    ["267062"] = {en = "Thalassian Tailor's Threads", zh = "萨拉斯裁缝华服"},
    ["267063"] = {en = "Pattern: Thalassian Tailor's Threads", zh = "图样：萨拉斯裁缝华服"},
    ["267076"] = {en = "Novice Combatant's Medallion", zh = "新手争斗者的饰章"},
    ["267077"] = {en = "Novice Combatant's Emblem", zh = "新手争斗者的纹章"},
    ["267082"] = {en = "Ornate Cosmic Table", zh = "华丽宇宙桌子"},
    ["267139"] = {en = "Hungry Black Hole", zh = "饥饿黑洞"},
    ["267177"] = {en = "Slayer's Duellum Commendation", zh = "屠戮角斗奖章"},
    ["267209"] = {en = "Open Void Elf Bedroll", zh = "打开的虚空精灵铺盖"},
    ["267235"] = {en = "Boon of Vitality", zh = "活力恩典"},
    ["267236"] = {en = "Boon of Speed", zh = "速度恩典"},
    ["267237"] = {en = "Boon of Power", zh = "能量恩典"},
    ["267238"] = {en = "Boon of Potency", zh = "效能恩典"},
    ["267239"] = {en = "Boon of Possibilities", zh = "或然恩典"},
    ["267240"] = {en = "Boon of Fortitude", zh = "坚忍恩典"},
    ["267241"] = {en = "Boon of Abstinence", zh = "节制恩典"},
    ["267242"] = {en = "Boon of Speed", zh = "速度恩典"},
    ["267243"] = {en = "Boon of Vitality", zh = "活力恩典"},
    ["267257"] = {en = "Cloak of the Hara'ti Sage", zh = "哈籁提贤者的斗篷"},
    ["267258"] = {en = "Cloak of the Hara'ti Seer", zh = "哈籁提先知的斗篷"},
    ["267259"] = {en = "Shoulderguards of the Hara'ti Sage", zh = "哈籁提贤者的护肩"},
    ["267260"] = {en = "Shoulderguards of the Hara'ti Seer", zh = "哈籁提先知的护肩"},
    ["267261"] = {en = "Tabard of the Hara'ti Sage", zh = "哈籁提贤者战袍"},
    ["267262"] = {en = "Tabard of the Hara'ti Seer", zh = "哈籁提先知战袍"},
    ["267265"] = {en = "Counterfeit Dark Heart of Galakrond", zh = "伪造的迦拉克隆幽暗之心"},
    ["267267"] = {en = "Ransacker's Netherhide Mask", zh = "洗劫者的虚空皮革面具"},
    ["267268"] = {en = "Dripping Silk Footwraps", zh = "滴水丝质裹足"},
    ["267270"] = {en = "Shadow-Drenched Legguards", zh = "浸影护腿"},
    ["267271"] = {en = "Nethersteel Deflectors", zh = "虚空钢铸偏斜腕甲"},
    ["267281"] = {en = "Plans: Blood Knight's Mercy", zh = "设计图：血骑士的慈悲"},
    ["267282"] = {en = "Plans: Blood Knight's Warblade", zh = "设计图：血骑士的战剑"},
    ["267284"] = {en = "Plans: Bloomforged Claw", zh = "设计图：绽铸之爪"},
    ["267285"] = {en = "Plans: Magister's Cleaver", zh = "设计图：魔导师的砍斧"},
    ["267286"] = {en = "Plans: Magister's Mana Sword", zh = "设计图：魔导师的法力之剑"},
    ["267287"] = {en = "Plans: Magister's Ritual Knife", zh = "设计图：魔导师的仪式之匕"},
    ["267291"] = {en = "Coffer Key Glue", zh = "宝匣钥匙粘合剂"},
    ["267299"] = {en = "Slayer's Duellum Trove", zh = "屠戮角斗财宝"},
    ["267371"] = {en = "Galactic Gladiator's Ripper", zh = "星河角斗士的裂肢拳刺"},
    ["267375"] = {en = "Galactic Aspirant's Claws", zh = "星河候选者的利爪"},
    ["267379"] = {en = "Tavern Mug", zh = "旅店酒杯"},
    ["267387"] = {en = "Test Item [DNT] - While you are poisoned", zh = "Test Item [DNT] - While you are poisoned"},
    ["267388"] = {en = "Test Item [DNT] - Apply Poison - Label", zh = "Test Item [DNT] - Apply Poison - Label"},
    ["267389"] = {en = "Test Item [DNT] - When you are poisoned", zh = "Test Item [DNT] - When you are poisoned"},
    ["267390"] = {en = "Test Item [DNT] - If target is poisoned", zh = "Test Item [DNT] - If target is poisoned"},
    ["267391"] = {en = "Test Item [DNT] - Dispelling a poison from target", zh = "Test Item [DNT] - Dispelling a poison from target"},
    ["267392"] = {en = "Test Item [DNT] - When you have poison dispelled from you", zh = "Test Item [DNT] - When you have poison dispelled from you"},
    ["267393"] = {en = "Radiant Shatter", zh = "光耀粉碎"},
    ["267394"] = {en = "Technique: Homely Sin'dorei Shelf", zh = "工艺图：家常辛多雷架子"},
    ["267395"] = {en = "Technique: Homely Wall Shelves", zh = "工艺图：家常壁挂搁架"},
    ["267399"] = {en = "Technique: Sturdy Ren'dorei Cask", zh = "工艺图：牢固的朗多雷木桶"},
    ["267400"] = {en = "Technique: Wild Hanging Scroll", zh = "工艺图：狂野悬挂卷轴"},
    ["267401"] = {en = "Dawn Shatter", zh = "黎明粉碎"},
    ["267403"] = {en = "Test Item [DNT] - Apply Poison - DISPEL TYPE", zh = "Test Item [DNT] - Apply Poison - DISPEL TYPE"},
    ["267417"] = {en = "Galactic Aspirant's Talons", zh = "星河候选者的爪甲"},
    ["267444"] = {en = "Smuggler's Cloak", zh = "走私者的斗篷"},
    ["267445"] = {en = "Silvermoon Agent's Drape", zh = "银月城特工的披风"},
    ["267446"] = {en = "Scout's Cape", zh = "斥候的披风"},
    ["267447"] = {en = "Farstrider's Embroidered Cover", zh = "远行者的刺绣罩布"},
    ["267448"] = {en = "Blood-Tempered Cape", zh = "淬血披风"},
    ["267449"] = {en = "Spellbreaker's Shroud", zh = "破法者的罩衣"},
    ["267456"] = {en = "Lil' Scoots' Pillow", zh = "小蹿蹿枕头"},
    ["267469"] = {en = "Novice Combatant's Insignia of Alacrity", zh = "新手争斗者的活跃徽记"},
    ["267479"] = {en = "Aspiring Hara'ti Defender's Sash", zh = "新晋哈籁提防御者的腰绳"},
    ["267480"] = {en = "Aspiring Hara'ti Defender's Cord", zh = "新晋哈籁提防御者的腰带"},
    ["267481"] = {en = "Aspiring Hara'ti Defender's Belt", zh = "新晋哈籁提防御者的腰索"},
    ["267482"] = {en = "Aspiring Hara'ti Defender's Greatbelt", zh = "新晋哈籁提防御者的重型腰带"},
    ["267486"] = {en = "Simple Cup", zh = "朴素的杯子"},
    ["267487"] = {en = "Ignited Torch", zh = "点燃的火把"},
    ["267491"] = {en = "Novice Combatant's Cloak", zh = "新手争斗者的披风"},
    ["267571"] = {en = "Conqueror's Galactic Varnish", zh = "征服者的星河清漆"},
    ["267572"] = {en = "Conqueror's Galactic Lacquer", zh = "征服者的星河火漆"},
    ["267573"] = {en = "Cracked Medal of Conquest", zh = "开裂的征服勋章"},
    ["267604"] = {en = "Clutches of the Colossal Behemoths", zh = "巨兽攫握"},
    ["267605"] = {en = "Neverending Vortex Grasps", zh = "无尽漩涡之握"},
    ["267606"] = {en = "Gloves of Infinite Gravity", zh = "无限引力手套"},
    ["267607"] = {en = "Hazy Penumbral Handwraps", zh = "朦胧半影裹手"},
    ["267614"] = {en = "Whispering Phial", zh = "低语瓶剂"},
    ["267615"] = {en = "Imperial Mug", zh = "皇家酒杯"},
    ["267617"] = {en = "Sophisticated Goblet", zh = "精致的高脚杯"},
    ["267618"] = {en = "Rusty Receptacle", zh = "生锈的容器"},
    ["267619"] = {en = "Sipping Glass", zh = "啜饮杯"},
    ["267620"] = {en = "Simple Stein", zh = "朴素啤酒杯"},
    ["267621"] = {en = "Traditional Stein", zh = "传统啤酒杯"},
    ["267622"] = {en = "Rugged Torch", zh = "粗糙的火把"},
    ["267623"] = {en = "Simple Torch", zh = "简易火把"},
    ["267624"] = {en = "Bamboo Tray", zh = "竹制托盘"},
    ["267625"] = {en = "Lit Candle", zh = "点燃的蜡烛"},
    ["267626"] = {en = "Stale Tavern Bread", zh = "陈年旅店面包"},
    ["267627"] = {en = "Decorative Tavern Cheese", zh = "装饰旅店奶酪"},
    ["267628"] = {en = "Historian's Tome", zh = "历史学家的书典"},
    ["267638"] = {en = "Tarnished Silvermoon Sunspire", zh = "褪色的银月城太阳之塔头冠"},
    ["267639"] = {en = "Tarnished Silvermoon Sunguard", zh = "褪色的银月城日卫护面"},
    ["267640"] = {en = "Tarnished Silvermoon Sunveil", zh = "褪色的银月城日纱兜帽"},
    ["267641"] = {en = "Tarnished Silvermoon Suncrest", zh = "褪色的银月城日顶头盔"},
    ["267642"] = {en = "Worn Amani Heartstring Pendant", zh = "破损的阿曼尼心弦吊坠"},
    ["267643"] = {en = "Worn Amani Totemstring", zh = "破损的阿曼尼图腾索"},
    ["267645"] = {en = "Dreamrift Vanquisher's Argent Trophy", zh = "梦境裂隙征服者的闪银战利品"},
    ["267646"] = {en = "March on Quel'Danas Vanquisher's Argent Trophy", zh = "进军奎尔丹纳斯征服者的闪银战利品"},
    ["267647"] = {en = "Boon of Vigor", zh = "活力恩典"},
    ["267648"] = {en = "Boon of Vigor", zh = "活力恩典"},
    ["267649"] = {en = "Boon of Vigor", zh = "活力恩典"},
    ["267650"] = {en = "Blood Knight Training Manual", zh = "血骑士训练手册"},
    ["267652"] = {en = "Silver Hand Squire's Libram", zh = "白银之手侍从的圣契"},
    ["267653"] = {en = "Glimmering Powder", zh = "微光粉末"},
    ["267654"] = {en = "Swirling Arcane Essence", zh = "盘旋奥术精华"},
    ["267655"] = {en = "Brimming Mana Shard", zh = "满溢法力碎片"},
    ["267838"] = {en = "Sunwing Hatchling", zh = "日翼雏龙"},
    ["268025"] = {en = "Heavy Stein", zh = "厚重啤酒杯"},
    ["268032"] = {en = "Conjured Illusory Adornment - Blooming Light", zh = "召唤的幻影魔饰 - 光绽"},
    ["268033"] = {en = "Conjured Illusory Adornment - Nature's Embrace", zh = "召唤的幻影魔饰 - 自然的拥抱"},
    ["268034"] = {en = "Conjured Illusory Adornment - Voidtouched", zh = "召唤的幻影魔饰 - 虚触"},
    ["268038"] = {en = "Endless Codex of Blooming Light", zh = "繁盛之光无尽法典"},
    ["268039"] = {en = "Endless Codex of Nature's Grace", zh = "自然的优雅无尽法典"},
    ["268041"] = {en = "Endless Codex of the Voidtouched", zh = "虚触无尽法典"},
    ["268042"] = {en = "Formula: Endless Codex of Blooming Light", zh = "公式：繁盛之光无尽法典"},
    ["268043"] = {en = "Formula: Endless Codex of Nature's Grace", zh = "公式：自然的优雅无尽法典"},
    ["268044"] = {en = "Formula: Endless Codex of the Voidtouched", zh = "公式：虚触无尽法典"},
    ["268049"] = {en = "Voidspire Vanquisher's Argent Trophy", zh = "虚影尖塔征服者的闪银战利品"},
    ["268053"] = {en = "Rugged Cup", zh = "粗糙的杯子"},
    ["268068"] = {en = "Sturdy Torch", zh = "坚固的火把"},
    ["268085"] = {en = "Hand Torch", zh = "手持火把"},
    ["268110"] = {en = "Cheese Tray", zh = "奶酪托盘"},
    ["268111"] = {en = "Arkonite Beacon", zh = "阿肯尼特信标"},
    ["268112"] = {en = "Argunite Beacon", zh = "阿古尼特信标"},
    ["268115"] = {en = "Overbaked Donut", zh = "烤焦的甜甜圈"},
    ["268116"] = {en = "Twin-Flame Holder", zh = "双火烛台"},
    ["268274"] = {en = "Blinky's Collar", zh = "闪闪的项圈"},
    ["268297"] = {en = "Rattling Bag o' Gold", zh = "叮当作响的金币袋"},
    ["268326"] = {en = "Sin'dorei Citizen's Cloak", zh = "辛多雷市民的斗篷"},
    ["268327"] = {en = "Sin'dorei Citizen's Shawl", zh = "辛多雷市民的披肩"},
    ["268365"] = {en = "Thalassian Competitor's Staff", zh = "萨拉斯竞争者的法杖"},
    ["268366"] = {en = "Technique: Thalassian Competitor's Staff", zh = "工艺图：萨拉斯竞争者的法杖"},
    ["268368"] = {en = "Fragmented Memento of Epoch Challenges", zh = "粉碎的纪元挑战纪念品"},
    ["268475"] = {en = "Evercore Dome Dinger", zh = "永恒之核圆顶发射器"},
    ["268477"] = {en = "P.O.W. x3", zh = "P.O.W. x3"},
    ["268479"] = {en = "Thalassian Competitor's Rifle", zh = "萨拉斯竞争者的步枪"},
    ["268480"] = {en = "Schematic: Thalassian Competitor's Rifle", zh = "结构图：萨拉斯竞争者的步枪"},
    ["268485"] = {en = "Victorious Stormarion Pinnacle Cache", zh = "胜利的斯托玛兰巅峰之箱"},
    ["268487"] = {en = "Avid Learner's Supply Pack", zh = "好学者的补给包"},
    ["268488"] = {en = "Overflowing Abundant Satchel", zh = "满溢的丰饶背包"},
    ["268489"] = {en = "Surplus Bag of Party Favors", zh = "盈余的派对礼品袋"},
    ["268490"] = {en = "Apex Cache", zh = "顶点宝匣"},
    ["268534"] = {en = "Sanctum's Decree", zh = "秘殿法令"},
    ["268545"] = {en = "Aspiring Preyseeker's Chest", zh = "新晋寻猎者宝箱"},
    ["268551"] = {en = "Scroll of Reflection", zh = "沉思卷轴"},
    ["268679"] = {en = "Hearty Impossibly Royal Roast", zh = "丰盛的异乎寻常的皇家烤肉"},
    ["268680"] = {en = "Hearty Flora Frenzy", zh = "丰盛植物狂宴"},
    ["268695"] = {en = "Pin-o-Matic Camera", zh = "钉图相机"},
    ["268717"] = {en = "Pango Plating", zh = "穿山甲鳞板"},
    ["268728"] = {en = "Saptor Salve", zh = "迅叶龙药膏"},
    ["268730"] = {en = "Nether-Warped Egg", zh = "虚空扭曲之蛋"},
    ["268921"] = {en = "Staff of the Great Dark", zh = "巨暗法杖"},
    ["268954"] = {en = "Entropic Extract", zh = "熵能萃取物"},
    ["268955"] = {en = "Entropic Extract", zh = "熵能萃取物"},
    ["269005"] = {en = "Preyseeker's Glinting Coin Pouch", zh = "寻猎者的闪光钱袋"},
    ["269006"] = {en = "Preyseeker's Gleaming Coin Pouch", zh = "寻猎者的烁光钱袋"},
    ["269007"] = {en = "Preyseeker's Glittering Coin Pouch", zh = "寻猎者的灿烂钱袋"},
    ["269009"] = {en = "Golden Ashened Cataclysm", zh = "金色烬灭灾变者"},
    ["269010"] = {en = "Essence of Lumber", zh = "木料精华"},
    ["269022"] = {en = "Healing Waters of Ahl'ua", zh = "奥露阿的治愈之水"},
    ["269023"] = {en = "Phytogenic Poison Part", zh = "植源毒物器官"},
    ["269028"] = {en = "Sootpaw", zh = "炭爪"},
    ["269269"] = {en = "Devouring Ritual Spire", zh = "吞噬军团仪式高塔"},
    ["269586"] = {en = "Emergency Soul Link", zh = "应急灵魂链接"},
    ["269603"] = {en = "Verdant Stalker Sludge", zh = "青翠追猎者之泥"},
    ["269606"] = {en = "Borrowed Wand", zh = "借来的魔杖"},
    ["269701"] = {en = "Surplus Bag of Party Favors", zh = "盈余的派对礼品袋"},
    ["269702"] = {en = "Overflowing Abundant Satchel", zh = "满溢的丰饶背包"},
    ["269703"] = {en = "Avid Learner's Supply Pack", zh = "好学者的补给包"},
    ["269704"] = {en = "Victorious Stormarion Cache", zh = "胜利的斯托玛兰宝箱"},
    ["269743"] = {en = "Landro's Golden Loot Box", zh = "兰德鲁的金色豪华礼物盒"},
    ["269897"] = {en = "Ascension Arrestor's Crossbow", zh = "重型荆棘弩"},
    ["269898"] = {en = "Ascension Agitator's Crossbow", zh = "重型荆棘弩"},
    ["269972"] = {en = "Arathi Miner's Pickaxe", zh = "阿拉希矿工的镐子"},
    ["269973"] = {en = "Warglaive of Unyielding Will", zh = "不屈意志战刃"},
    ["269974"] = {en = "Earthen Traveler's Crusher", zh = "土灵旅行者的碾压者"},
    ["269978"] = {en = "Earthen Traveler's Breaker", zh = "土灵旅行者的毁灭者"},
    ["269979"] = {en = "Grateful Goblin's Glaive", zh = "感恩地精的弯刃"},
    ["269980"] = {en = "Tuskcarver's Warglaive", zh = "獠牙雕刻者的战刃"},
    ["269981"] = {en = "Paintmaker's Edge", zh = "制漆者的锋刃"},
    ["269982"] = {en = "Spore-Touched Glaive", zh = "孢触弯刃"},
    ["269985"] = {en = "Azure Guardian's Sword", zh = "碧蓝守护者的长剑"},
    ["269986"] = {en = "Dreamer's Spellblade", zh = "沉睡者的魔刃"},
    ["269987"] = {en = "Vault Guard's Axe", zh = "宝库守卫的利斧"},
    ["269988"] = {en = "Peacekeeper's Axe", zh = "维和者的利斧"},
    ["269992"] = {en = "Sharpened Arcanite Warglaive", zh = "锋利的奥金战刃"},
    ["270430"] = {en = "Windpetal Haranir Crook", zh = "风瓣哈籁尼尔曲杖"},
    ["270431"] = {en = "Haranir Footlocker", zh = "哈籁尼尔手提箱"},
    ["270433"] = {en = "Dawnroot Haranir Quarterstaff", zh = "黎根哈籁尼尔短杖"},
    ["270439"] = {en = "Wildgrove Haranir Spear", zh = "荒林哈籁尼尔长矛"},
    ["270440"] = {en = "Rootbound Haranir Handaxe", zh = "根缚哈籁尼尔手斧"},
    ["270441"] = {en = "Thornpierce Haranir Chopper", zh = "荆刺哈籁尼尔砍斧"},
    ["270442"] = {en = "Rootbound Haranir Chopper", zh = "根缚哈籁尼尔砍斧"},
    ["270443"] = {en = "Wildbloom Haranir Bastion", zh = "荒花哈籁尼尔壁垒"},
    ["270444"] = {en = "Wildbloom Haranir Carver", zh = "荒花哈籁尼尔刻斧"},
    ["271616"] = {en = "Add Keystone Affix: Lindormi's Guidance", zh = "添加钥石词缀：林多尔米的指引"},
    ["271631"] = {en = "Light Guardian's Reward", zh = "圣光守卫者的奖赏"},
    ["271703"] = {en = "Title: Volunteer", zh = "头衔：志愿者"},
    ["271704"] = {en = "Title: Caring Citizen", zh = "头衔：热心市民"},
    ["271709"] = {en = "Title: The Backbone of the Realm", zh = "头衔：中流砥柱"},
    ["271710"] = {en = "Title: The Philanthropist", zh = "头衔：大慈善家"},
    ["271711"] = {en = "Title: The Everlasting", zh = "头衔：万世不朽"},
    ["271712"] = {en = "Title: World Apex", zh = "头衔：世界之巅"},
    ["271713"] = {en = "Title: Azeroth's Top Ten Youth", zh = "头衔：艾泽拉斯十佳青年"},
    ["271714"] = {en = "Title: Model of the Era", zh = "头衔：时代楷模"},
    ["271715"] = {en = "Title: Big Brother", zh = "头衔：带头大哥"},
}
